
TheoryCraft_SetBonuses = {
	["The Defiler's Intent"] = {
		[1] = {
			["pieces"] = 3,
			["text"] = "Improves your chance to get a critical strike with spells by 1%.",
		},
	},
	["Arcanist Regalia"] = {
		[1] = {
			["pieces"] = 3,
			["text"] = "Increases damage and healing done by magical spells and effects by up to 18.",
		},
		[2] = {
			["pieces"] = 5,
			["text"] = "Decreases the magical resistances of your spell targets by 10.",
		},
		[3] = {
			["pieces"] = 8,
			["text"] = "Decreases the threat generated by your spells by 15%.",
		},
	},
}
TheoryCraft_MitigationMobs = {
}
TheoryCraft_MitigationPlayers = {
}
