local L = LibStub("AceLocale-3.0"):NewLocale("Gladius", "frFR", true)

if L then

L["Action"] = "Action"
L["Action #%d"] = "Action #%d"
L["Add"] = "Ajouter"
L["Add new aura"] = "Ajouter une nouvelle aura"
L["ALT"] = "ALT"
L["Announce enemies that go below a certain percentage of health"] = "Announce enemies that go below a certain percentage of health." -- Requires localization
L["Announcements"] = "Annonces"
L["Announcement type"] = "Announcement type" -- Requires localization
L["Announce new enemies found"] = "Announce new enemies found." -- Requires localization
L["Announces enemies that start to drink"] = "Annonce les ennemis qui commencent à boire"
L["Announce when an enemy's trinket is ready again"] = "Announce when an enemy's trinket is ready again" -- Requires localization
L["Announce when an enemy's trinket is used"] = "Announce when an enemy's trinket is used" -- Requires localization
L["Arena "] = "Arène"
L["Aura list"] = "Liste des auras"
L["Auras"] = "Auras"
L["Aura text color"] = "Couleur du texte des auras"
L["Aura text size"] = "Taille du texte des auras"
L["Bar bottom margin"] = "Marge de la barre inférieure"
L["Bars"] = "Barres"
L["Bar settings"] = "Paramètres de la barre"
L["Bar texture"] = "Texture de la barre"
L["Bar width"] = "Largeur de la barre"
L["Big icon"] = "Big icon" -- Requires localization
L["Big icon scale"] = "Echelle des grandes icônes"
L["Blizzard's Floating Combat Text"] = "Texte de combats flottants de Blizzard"
L["Button"] = "Bouton"
L["Button 4"] = "Bouton 4"
L["Button 5"] = "Bouton 5"
L["Cast bar color"] = "Cast bar color" -- Requires localization
L["Cast bar height"] = "Cast bar height" -- Requires localization
L["Cast bar text color"] = "Cast bar text color" -- Requires localization
L["Cast bar text size"] = "Cast bar text size" -- Requires localization
L["Cast Spell"] = "Cast Spell" -- Requires localization
L["Choose how to display the trinket status"] = "Choose how to display the trinket status" -- Requires localization
L["Click actions"] = "Click actions" -- Requires localization
L["Clique support"] = "Clique support" -- Requires localization
L["Color of the aura text"] = "Color of the aura text" -- Requires localization
L["Color of the cast bar"] = "Color of the cast bar" -- Requires localization
L["Color of the cast bar text"] = "Color of the cast bar text" -- Requires localization
L["Color of the energy bar"] = "Couleur de la barre d'énergie"
L["Color of the focus border"] = "Color of the focus border" -- Requires localization
L["Color of the frame"] = "Color of the frame" -- Requires localization
L["Color of the health bar text"] = "Color of the health bar text" -- Requires localization
L["Color of the mana bar"] = "Couleur de la barre de mana"
L["Color of the mana bar text"] = "Color of the mana bar text" -- Requires localization
L["Color of the pet bar"] = "Color of the pet bar" -- Requires localization
L["Color of the rage bar"] = "Couleur de la barre de rage"
L["Color of the runic power bar"] = "Color of the runic power bar" -- Requires localization
L["Color of the selected targets border"] = "Color of the selected targets border" -- Requires localization
L["Color of the text on the pet bar"] = "Color of the text on the pet bar" -- Requires localization
L["Colors"] = "Couleurs et textures"
L["Color settings"] = "Réglages des couleurs et textures"
L["CTRL"] = "CTRL"
L["Delete"] = "Effacer"
L["Drinking"] = "Boire"
L["DRINKING: %s (%s)"] = "Boire: %s (%s)"
L["Enemies on low health"] = "Enemies on low health" -- Requires localization
L["Energy color"] = "Energy color" -- Requires localization
L["First run has been detected, displaying test frame."] = "First run has been detected, displaying test frame." -- Requires localization
L["Focus border color"] = "Focus border color" -- Requires localization
L["Frame color"] = "Frame color" -- Requires localization
L["Frame padding"] = "Frame padding" -- Requires localization
L["Frame resize"] = "Frame resize" -- Requires localization
L["Frame scale"] = "Frame scale" -- Requires localization
L["Game default"] = "Game default" -- Requires localization
L["General"] = "General" -- Requires localization
L["General settings"] = "General settings" -- Requires localization
L["Gladius"] = "Gladius" -- Requires localization
L["Gladius - drag to move"] = "Gladius - drag to move" -- Requires localization
L["/gladius test1-5"] = "/gladius test1-5"
L["/gladius ui"] = "/gladius ui"
L["Grid-style icon"] = "Grid-style icon" -- Requires localization
L["Grow frame upwards"] = "Grow frame upwards" -- Requires localization
L["Health bar height"] = "Health bar height" -- Requires localization
L["Health text color"] = "Health text color" -- Requires localization
L["Health text size"] = "Health text size" -- Requires localization
L["Height of the cast bars"] = "Height of the cast bars" -- Requires localization
L["Height of the health bars"] = "Height of the health bars" -- Requires localization
L["Height of the pet bars"] = "Height of the pet bars" -- Requires localization
L["Height of the power bars"] = "Height of the power bars" -- Requires localization
L["Highlight target"] = "Highlight target" -- Requires localization
L["If this is enabled the frame will automaticly get resized to the appropriate size every time you enter an arena"] = "If this is enabled the frame will automaticly get resized to the appropriate size every time you enter an arena" -- Requires localization
L["If this is not your first run please lock or move the frame to prevent this from happening."] = "If this is not your first run please lock or move the frame to prevent this from happening." -- Requires localization
L["If this is toggled the frame will grow upwards instead of downwards."] = "If this is toggled the frame will grow upwards instead of downwards." -- Requires localization
L["Left button"] = "Left button" -- Requires localization
L["Left click enemy #1"] = "Left click enemy #1" -- Requires localization
L["Left click enemy #2"] = "Left click enemy #2" -- Requires localization
L["Left click enemy #3"] = "Left click enemy #3" -- Requires localization
L["Left click enemy #4"] = "Left click enemy #4" -- Requires localization
L["Left click enemy #5"] = "Left click enemy #5" -- Requires localization
L["Lock frame"] = "Lock frame" -- Requires localization
L["Low health percentage"] = "Low health percentage" -- Requires localization
L["LOW HEALTH: %s"] = "LOW HEALTH: %s" -- Requires localization
L["Mana color"] = "Mana color" -- Requires localization
L["Mana text color"] = "Mana text color" -- Requires localization
L["Mana text size"] = "Mana text size" -- Requires localization
L["Margin to the next bar"] = "Margin to the next bar" -- Requires localization
L["Middle button"] = "Middle button" -- Requires localization
L["MikScrollingBattleText"] = "MikScrollingBattleText" -- Requires localization
L["Modifier"] = "Modifier" -- Requires localization
L["Name"] = "Name" -- Requires localization
L["Name icon"] = "Name icon" -- Requires localization
L["Name of the aura"] = "Name of the aura" -- Requires localization
L["Name text"] = "Name text" -- Requires localization
L["New enemies"] = "New enemies" -- Requires localization
L["None"] = "None" -- Requires localization
L["Override class/aura icon"] = "Override class/aura icon" -- Requires localization
L["Padding of the frame"] = "Padding of the frame" -- Requires localization
L["Party"] = "Party" -- Requires localization
L["Pet bar color"] = "Pet bar color" -- Requires localization
L["Pet bar height"] = "Pet bar height" -- Requires localization
L["Pet bar text color"] = "Pet bar text color" -- Requires localization
L["Pet bar text size"] = "Pet bar text size" -- Requires localization
L["Pet bar width"] = "Pet bar width" -- Requires localization
L["Power bar height"] = "Power bar height" -- Requires localization
L["Priority"] = "Priority" -- Requires localization
L["Rage color"] = "Rage color" -- Requires localization
L["Raid Warning"] = "Raid Warning" -- Requires localization
L["Right button"] = "Right button" -- Requires localization
L["Right click enemy #1"] = "Right click enemy #1" -- Requires localization
L["Right click enemy #2"] = "Right click enemy #2" -- Requires localization
L["Right click enemy #3"] = "Right click enemy #3" -- Requires localization
L["Right click enemy #4"] = "Right click enemy #4" -- Requires localization
L["Right click enemy #5"] = "Right click enemy #5" -- Requires localization
L["Runic Power color"] = "Runic Power color" -- Requires localization
L["Scale of the frame"] = "Scale of the frame" -- Requires localization
L["Scrolling Combat Text"] = "Scrolling Combat Text" -- Requires localization
L["Selected border color"] = "Selected border color" -- Requires localization
L["Select the name of the click option"] = "Select the name of the click option" -- Requires localization
L["Select what action this mouse button does"] = "Select what action this mouse button does" -- Requires localization
L["Select what priority the aura should have - higher equals more priority"] = "Priority" -- Requires localization
L["Select which modifier to use"] = "Select which modifier to use" -- Requires localization
L["Select which mouse button to use"] = "Select which mouse button to use" -- Requires localization
L["Set options for different announcements"] = "Set options for different announcements" -- Requires localization
L["Set options for mouse clicks on the arena targets"] = "Set options for mouse clicks on the arena targets" -- Requires localization
L["Set options for the trinket status display"] = "Set options for the trinket status display" -- Requires localization
L["SHIFT"] = "SHIFT" -- Requires localization
L["Shorten Health/Power text"] = "Shorten Health/Power text" -- Requires localization
L["Shorten the formatting of the health and power text to e.g. 20.0/25.3 when the amount is over 9999"] = "Shorten the formatting of the health and power text to e.g. 20.0/25.3 when the amount is over 9999" -- Requires localization
L["Show auras"] = "Show auras" -- Requires localization
L["Show border around focus"] = "Show border around focus" -- Requires localization
L["Show border around target"] = "Show border around target" -- Requires localization
L["Show cast bars"] = "Show cast bars" -- Requires localization
L["Show class icon"] = "Show class icon" -- Requires localization
L[ [=[Show class icon
IMPORTANT:
Toggling this off will disable showing auras even if it is enabled]=] ] = [=[Show class icon
IMPORTANT:
Toggling this off will disable showing auras even if it is enabled]=] -- Requires localization
L["Show class text"] = "Show class text" -- Requires localization
L["Show class text on the power bar"] = "Show class text on the power bar" -- Requires localization
L["Show health percentage"] = "Show health percentage" -- Requires localization
L["Show health percentage on the health bar"] = "Show health percentage on the health bar" -- Requires localization
L["Show important auras over the class icon with a timer. You can select which auras to show and their respective priorites in the auralist.lua file"] = "Show important auras over the class icon with a timer. You can select which auras to show and their respective priorites the Aura category to the left." -- Requires localization
L["Show mana/energy/rage percentage on the power bar"] = "Show mana/energy/rage percentage on the power bar" -- Requires localization
L["Show mana/energy/rage text on the power bar"] = "Show mana/energy/rage text on the power bar" -- Requires localization
L["Show max health"] = "Show max health" -- Requires localization
L["Show maximum health on the health bar"] = "Show maximum health on the health bar" -- Requires localization
L["Show maximum mana/energy/rage on the power bar"] = "Show maximum mana/energy/rage on the power bar" -- Requires localization
L["Show max power"] = "Show max power" -- Requires localization
L["Show pet bars"] = "Show pet bars" -- Requires localization
L["Show pet health on the pet bar (formatted the same as the ordinary health text)"] = "Show pet health text (formatted the same as the ordinary health text)" -- Requires localization
L["Show pet health text"] = "Show pet health text" -- Requires localization
L["Show pet type on the pet bar"] = "Show pet type text" -- Requires localization
L["Show pet type text"] = "Show pet type text" -- Requires localization
L["Show power bars"] = "Show power bars" -- Requires localization
L["Show power percentage"] = "Show power percentage" -- Requires localization
L["Show power text"] = "Show power text" -- Requires localization
L["Show PvP trinket status"] = "Show PvP trinket status" -- Requires localization
L["Show PvP trinket status to the right of the enemy name"] = "Show PvP trinket status to the right of the enemy name" -- Requires localization
L["Show race text"] = "Show race text" -- Requires localization
L["Show race text on the power bar"] = "Show race text on the power bar" -- Requires localization
L["Show target icon"] = "Show target icon" -- Requires localization
L["Show the actual health"] = "Show the actual health" -- Requires localization
L["Show the actual health on the health bar"] = "Show the actual health on the health bar" -- Requires localization
L["Show the actual mana/energy/rage on the power bar"] = "Show the actual mana/energy/rage on the power bar" -- Requires localization
L["Show the actual power"] = "Show the actual power" -- Requires localization
L["Size and margin"] = "Size and margin" -- Requires localization
L["Size and margin settings"] = "Size and margin settings" -- Requires localization
L["Size of the aura text"] = "Size of the aura text" -- Requires localization
L["Size of the cast bar text"] = "Size of the cast bar text" -- Requires localization
L["Size of the health bar text"] = "Size of the health bar text" -- Requires localization
L["Size of the mana bar text"] = "Size of the mana bar text" -- Requires localization
L["Size of the pet bar text"] = "Size of the pet bar text" -- Requires localization
L["Sizes"] = "Sizes" -- Requires localization
L["Size settings for the text"] = "Size settings for the text" -- Requires localization
L["Small icon"] = "Small icon" -- Requires localization
L["Spell name / Macro text"] = "Spell name / Macro text" -- Requires localization
L["Text"] = "Text" -- Requires localization
L["Text settings"] = "Text settings" -- Requires localization
L["The percentage when enemies are counted as having low health"] = "The percentage when enemies are counted as having low health" -- Requires localization
L["The scale of the big trinket icon"] = "The scale of the big trinket icon" -- Requires localization
L["Toggle if a border should be shown around the selected target"] = "Toggle if a border should be shown around the selected target" -- Requires localization
L["Toggle if a border should be shown around your current focus"] = "Toggle if a border should be shown around your current focus" -- Requires localization
L["Toggle if the frame can be moved"] = "Toggle if the frame can be moved" -- Requires localization
L["Toggle if the selected target should be highlighted"] = "Toggle if the selected target should be highlighted" -- Requires localization
L["Toggles the Clique support, requires UI reload to take effect"] = "Toggles the Clique support, requires UI reload to take effect" -- Requires localization
L["Trinket display"] = "Trinket display" -- Requires localization
L["Trinket ready"] = "Trinket ready" -- Requires localization
L["TRINKET READY: %s (%s)"] = "TRINKET READY: %s (%s)" -- Requires localization
L["Trinket used"] = "Trinket used" -- Requires localization
L["TRINKET USED: %s (%s)"] = "TRINKET USED: %s (%s)" -- Requires localization
L["Use game default energy color"] = "Use game default energy color" -- Requires localization
L["Use game default mana color"] = "Use game default mana color" -- Requires localization
L["Use game default rage color"] = "Use game default rage color" -- Requires localization
L["Use game default runic power color"] = "Use game default runic power color" -- Requires localization
L["Valid slash commands are:"] = "Valid slash commands are:" -- Requires localization
L["Welcome to Gladius!"] = "Welcome to Gladius!" -- Requires localization
L["Where to display the announcement messages"] = "Where to display the announcement messages" -- Requires localization
L["Width of the health and power bars"] = "Width of the health and power bars" -- Requires localization
L["Width of the pet bars"] = "Width of the pet bars" -- Requires localization

end
