--  Translation courtesy of Stan (Arcádia - EU Zirkel des Cenarius), kunda
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Omen", "deDE")
if not L then return end
L["Background color"] = "Hintergrundfarbe"
L["Background texture"] = "Hintergrundtextur"
L["Bar options"] = "Balkenoptionen"
L["Border color"] = "Randfarbe"
L["Border texture"] = "Randtextur"
L["Color"] = "Farbe"
L["Configure"] = "Einstellen"
L["Configure the labels that appear on the bars"] = "Balkentext der Balken anpassen"
L["Control the label fonts"] = "Einstellungen für die Schriftart des Balkentextes"
L["Control the font size of the labels"] = "Einstellungen für die Schriftgröße des Balkentextes"
L["Display options"] = "Anzeigeoptionen"
L["Font"] = "Schriftart"
L["Font settings"] = "Einstellungen der Schriftart"
L["Frame's border color"] = "Randfarbe des Rahmens"
L["Height"] = "Höhe"
L["Height of each bar"] = "Balkenhöhe"
L["Labels"] = "Balkentext"
L["Window options"] = "Fensteroptionen"
L["None"] = "Keine"
L["Open the configuration dialog"] = "Den Konfigurationsdialog öffnen"
L["Options that control Omen's appearance"] = "Optionen um das Aussehen von Omen bestimmen"
L["Options for modifying the look and feel of the main display"] = "Optionen um das Aussehen und Verhalten des Hauptfensters anzupassen"
L["Options which affect the style of the threat bars"] = "Optionen, die das Aussehen der Bedrohungsbalken betreffen"
L["Outline"] = "Kontur"
L["Size"] = "Größe"
L["Control the size of this frame"] = "Die Größe dieses Rahmens bestimmen"
L["Spacing"] = "Abstand"
L["Spacing between each bar"] = "Abstand zwischen den Balken"
L["Stretch textures"] = "Texturen strecken"
L["Stretch textures to fit the width of the bar"] = "Texturen strecken um sie an die Breite des Balkens anzupassen"
L["Texture"] = "Textur" 
L["Thick Outline"] = "Dicke Kontur"
L["The color of the labels"] = "Die Farbe des Balkentextes"
L["The font that the labels will use"] = "Die Schriftart die der Balkentext benutzen wird"
L["The outline that the labels will use"] = "Die Kontur die der Balkentext benutzen wird"
L["The texture that the bar will use"] = "Die Textur die die Balken benutzen werden"

L["Texture to use for the frame's background"] = "Textur die für den Hintergrund des Rahmens verwendet wird"
L["Texture to use for the frame's border"] = "Textur die für den Rand des Rahmens verwendet wird"
L["Main display's border color"] = "Randfarbe des Hauptfensters"
L["Bars window"] = "Balkenfenster"
L["Options that affect the appearance of the bar list window"] = "Optionen, die das Aussehen des Balkenfensters betreffen"
L["Options that affect the appearance of the title window"] = "Optionen, die das Aussehen des Titelfensters betreffen"
L["Options that affect the appearance of the module list window"] = "Optionen, die das Aussehen des Modulfensters betreffen"
L["Title window"] = "Titelfenster"
L["Hide version"] = "Versionsnummer verstecken"
L["Hide the version number and out-of-date notice"] = "Versionsnummer und die veraltete-Version-Meldung verstecken"
L["Hide"] = "Verstecken"
L["Hide this frame"] = "Diesen Rahmen verstecken"
L["Options not related to appearance"] = "Optionen die nichts mit dem Aussehen zu tun haben"
L["General options"] = "Allgemeine Einstellungen"
L["TPS Update Frequency"] = "BPS Aktualisierungsrate"
L["Controls the speed at which TPS (threat per second) values update.\nRaise this value to increase performance, or set it to 0 to turn off TPS queries."] = "Bestimmt die Geschwindigkeit der Aktualisierung für BPS (Bedrohung pro Sekunde) Werte.\nErhöhe diesen Wert für bessere Performance oder setze ihn auf 0 um die BPS Berechnung auszuschalten."
L["Modules window"] = "Modulfenster"
L["Defaults"] = "Werkseinstellungen"
L["Options that affect the appearance of all frames"] = "Optionen, die das Aussehen aller Rahmen betreffen"
L["Reset to defaults"] = "Auf Werkseinstellungen zurücksetzen"
L["Use global defaults for this frame"] = "Verwende globale Einstellungen für diesen Rahmen"
L["Show test bars"] = "Zeige Testbalken"
L["Test"] = "Test"

L["Modules"] = "Module"
L["Options for Omen's various modules"] = "Optionen für die verschiedenen Omen Module"

L["Lock Omen"] = "Omen verankern"
L["Locks Omen in place and prevents it from being dragged or resized."] = "Verankert Omen an der momentanen Position um zu verhindern, daß das Fenster verschoben oder die Größe verändert wird."
L["Hide when not needed"] = "Verstecke wenn nicht gebraucht"

L["Animate bars"] = "Balken animieren"
L["Smoothly animate bar changes"] = "Weich animierte Balkenveränderung"
L["Hides Omen when you are resting, not in a party, or in an arena or battleground"] = "Versteckt Omen wenn man ausruht, nicht in einer Gruppe, Arena oder Schlachtfeld ist."
L["Error"] = "Fehler"
L["Unable to use shake warning. If you have nameplates turned on, turn them off to enable shake warnings."] = "Die Wackelwarnungen können nicht verwendet werden, wenn die Namensplaketten aktiviert sind. Bitte schalte diese aus um Wackelwarnungen zu ermöglichen."

L["Background opacity"] = "Hintergrund Transparenz"
L["Opacity of each bar's background"] = "Hintergrund Transparenz der Balken"
L["Background darkness"] = "Hintergrund Dunkelheit"
L["Darkness of each bar's background"] = "Hintergrund Dunkelheit der Balken"

L["Opacity"] = "Transparenz"
L["Opacity of the entire frame"] = "Transparenz des gesamten Fensters"

L["Classes"] = "Klassen"
L["DRUID"] = "Druide"
L["HUNTER"] = "Jäger"
L["MAGE"] = "Magier"
L["PALADIN"] = "Paladin"
L["PET"] = "Begleiter"
L["PRIEST"] = "Priester"
L["ROGUE"] = "Schurke"
L["SHAMAN"] = "Schamane"
L["WARLOCK"] = "Hexenmeister"
L["WARRIOR"] = "Krieger"

L["Number of bars to show"] = "Anzahl der Balken"
L["Autocollapse"] = "Automatisches Zusammenklappen"
L["Collapse to show a minimum number of bars"] = "Autom. Zusammenklappen um eine minimale Anzahl von Balken zu zeigen"

L["Collapse hides bar list"] = "Zusammenklappen versteckt Balkenfenster"
L["Let autocollapse hide the bar list if no bars are shown"] = "Autom. Zusammenklappen versteckt die Balkenliste, wenn keine Balken angezeigt werden"
L["Collapse hides entire Omen window"] = "Zusammenklappen versteckt ganzes Fenster"
L["Let autocollapse hide the |c00ffffffentire window|r if no bars are shown. Note: This |c00ffffffwill|r prevent you from switching modules out of combat."] = "Autom. Zusammenklappen versteckt das |c00ffffffganze Fenster|r. Achtung: Es ist dann nur noch im Kampf möglich zwischen Modulen zu wechseln."

L["Grow Up"] = "Nach oben aufbauen"
L["Grow bars upwards"] = "Balken nach oben hin aufbauen"
L["Toggle Omen"] = "Omen ein-/ausblenden"
L["Center Omen"] = "Omen zentrieren"
L["Active when alone"] = "Aktiviert wenn alleine"
L["Enable ThreatLib even when you aren't in a party and don't have a pet."] = "Aktiviert die ThreatLib auch dann, wenn man in keiner Gruppe ist oder keinen Begleiter hat."

L["Control the scale of the entire Omen GUI"] = "Ändere die Skalierung des gesamten Omen Fensters"
L["Scale"] = "Skalierung"

L["Clamp to screen"] = "Auf Bildschirm arretieren"
L["Clamp the Omen frame to the screen"] = "Arretiert das Omen Fenster auf dem Bildschirm (verhindert das Verschieben über den Bildschirmrand)"

L["Skin"] = "Skin"
L["Save your current settings and load other skins"] = "Speichert Deine momentanen Einstellungen und lädt andere Skins"
L["Load Skin..."] = "Skin laden..."
L["Load a saved skin"] = "Einen gespeicherten Skin laden"
L["Save Skin As..."] = "Skin speichern als..."
L["Save the current settings as a skin"] = "Speichert die momentanen Einstellungen als Skin"

L["Click|r to toggle the Omen window"] = "Klicken|r um das Omen Fenster ein-/auszublenden"
L["Right-click|r to open the options menu"] = "Rechts-Klick|r um das Optionsfenster zu öffnen"

L["Attach to minimap"] = "An der Minikarte anbringen"
L["FuBar options"] = "FuBar Optionen"
L["Position"] = "Position"
L["Left"] = "Links"
L["Center"] = "Mitte"
L["Right"] = "Rechts"
L["Show text"] = "Text anzeigen"
L["Show icon"] = "Icon anzeigen"

L["Standby"] = "Ruhemodus"
L["Hide minimap/FuBar icon"] = "Minimap/FuBar Icon verstecken"

L["Configure Omen"] = "Omen konfigurieren"

L["Version Checks"] = "Versions Check"
L["Show all party member revisions"] = "Zeige alle Versionen"
L["Show oudated party member revisions"] = "Zeige veraltete Versionen"

L["ThreatLib Version Check: All party members"] = "ThreatLib Versions Check: Alle Gruppenmitglieder"
L["ThreatLib Version Check: Outdated party members"] = "ThreatLib Versions Check: Veraltete Versionen"
L["latest is"] = "die neueste ist"

L["You have a pet"] = "Du ein Begleiter hast"
L["Show Omen when you have a pet out"] = "Zeigt Omen, wenn Du ein Begleiter an Deiner Seite hast"
L["You are alone"] = "Du allein bist"
L["Show Omen when you are alone"] = "Zeigt Omen, wenn Du allein bist"
L["You are in a party"] = "Du in einer Gruppe bist"
L["Show Omen when you are in a 5-man party"] = "Zeigt Omen, wenn Du in einer 5er Gruppe bist"
L["You are in a raid"] = "Du in einer Schlachtgruppe bist"
L["Show Omen when you are in a raid"] = "Zeigt Omen, wenn du in einer Schlachtgruppe ist"
L["Show when..."] = "Zeige Omen, wenn..."
L["Show Omen when..."] = "Zeige Omen, wenn..."
L["You are resting"] = "Du Dich ausruhst"
L["Show Omen when you are resting"] = "Zeigt Omen, wenn Du Dich ausruhst"
L["You are in a battleground"] = "Du auf einem Schlachtfeld bist" 
L["Show Omen when you are in a battleground or arena"] = "Zeigt Omen, wenn Du auf einem Schlachtfeld oder in der Arena bist" 
L["You are in a dungeon"] = "Du in einer Instanz bist"
L["Show Omen when you are in a dungeon (5 man and raid)"] = "Zeigt Omen, wenn Du in einer Instanz bist (5er und Schlachtgruppe)"

L["Unknown"] = "Unbekannt"
L["Not compatible!"] = "Nicht kompatibel!"

L["Issue threat clear"] = "Bedrohungsliste löschen"
L["Issue threat clear (requires party leader or raid assistant)"] = "Bedrohungsliste manuell bei einem Problem löschen (benötigt Schlachtgruppenleiter oder -assistent)"

L["Your version of Omen/Threat is out of date. Please update from WAU or http://files.wowace.com/Omen/Omen.zip when possible."] = "Deine Omen/Threat Version ist veraltet. Wenn möglich, bitte mit WAU oder http://files.wowace.com/Omen/Omen.zip updaten."
L["Your version of Omen/Threat is out of date and is not compatible with the newest version. You should update from WAU or http://files.wowace.com/Omen/Omen.zip as soon as possible."] = "Deine Omen/Threat Version ist veraltet und nicht kompatibel mit der neuesten Version. Du solltest so schnell wie möglich mit WAU oder http://files.wowace.com/Omen/Omen.zip updaten."

L["Whisper older clients informing them to update."] = "Benutzer mit älteren Versionen mittels flüstern über einen Update informieren"
L["You must be the group leader or a group assistant to do this."] = "Du musst Schlachtgruppenleiter oder -assistent sein."

BINDING_HEADER_OMEN = "Omen"
BINDING_NAME_OMENTOGGLE = "Omen ein-/auszublenden"
BINDING_NAME_OMENNEXTMODULE = "Zum nächsten Modul"
BINDING_NAME_OMENPREVMODULE = "Zum vorherigen Modul"