local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Omen", "esES")
if not L then return end
-- Initial translation courtesy of maqjav - Marosth
L["Background color"] = "Color del fondo"
L["Background texture"] = "Textura de fondo"
L["Bar options"] = "Opciones barras"
L["Border color"] = "Color del borde"
L["Border texture"] = "Textura del borde"
L["Color"] = "Color"
L["Configure"] = "Configurar"
L["Configure the labels that appear on the bars"] = "Configura las etiquetas que aparecen en las barras"
L["Control the label fonts"] = "Controla la fuente de las etiquetas"
L["Control the font size of the labels"] = "Controla el tamaño de la fuente de las etiquetas"
L["Display options"] = "Opciones display"
L["Font"] = "Fuente"
L["Font settings"] = "Opciones de fuente"
L["Frame's border color"] = "Color del marco del borde"
L["Height"] = "Altura"
L["Height of each bar"] = "Altura de cada barra"
L["Labels"] = "Etiquetas"
L["Window options"] = "Opciones de ventana"
L["None"] = "Ningún"
L["Open the configuration dialog"] = "Abre el diálogo de configuración"
L["Options that control Omen's appearance"] = "Opciones sobre la apariencia del Omen"
L["Options for modifying the look and feel of the main display"] = "Opciones para modificar el aspecto del display principal"
L["Options which affect the style of the threat bars"] = "Opciones que afectan al estilo de las barras de amenaza"
L["Outline"] = "Contorno"
L["Size"] = "Tamaño"
L["Control the size of this frame"] = "Controla el tamaño de este marco"
L["Spacing"] = "Espaciado"
L["Spacing between each bar"] = "Espaciar entre cada barra"
L["Stretch textures"] = "Estirar texturas"
L["Stretch textures to fit the width of the bar"] = "Estirar texturas para llenar la anchura de la barra"
L["Texture"] = "Textura" 
L["Thick Outline"] = "Contorno grueso"
L["The color of the labels"] = "Color de las etiquetas"
L["The font that the labels will use"] = "La fuente que usarán las etiquetas"
L["The outline that the labels will use"] = "El contorno que usarán las etiquetas"
L["The texture that the bar will use"] = "La textura que usarán las barras"

L["Texture to use for the frame's background"] = "Textura a usar en el marco del fondo"
L["Texture to use for the frame's border"] = "Textura a usar en el marco del borde"
L["Main display's border color"] = "Color del borde del display principal"
L["Bars window"] = "Ventana de barras"
L["Options that affect the appearance of the bar list window"] = "Opciones que afectan a la apariencia de la ventana del listado de barras"
L["Options that affect the appearance of the title window"] = "Opciones que afectan a la apariencia de la ventana del título"
L["Options that affect the appearance of the module list window"] = "Opciones que afectan a la apariencia de la ventana del listado de módulos"
L["Title window"] = "Ventana del título"
L["Hide version"] = "Esconder versión"
L["Hide the version number and out-of-date notice"] = "Esconder el número de la versión y el mensaje fuera-de-fecha"
L["Hide"] = "Esconder"
L["Hide this frame"] = "Esconder este marco"
L["Options not related to appearance"] = "Opciones no relacionadas con apariencia"
L["General options"] = "Opciones generales"
L["TPS Update Frequency"] = "Frecuencia de actualizar la APS"
L["Controls the speed at which TPS (threat per second) values update.\nRaise this value to increase performance, or set it to 0 to turn off TPS queries."] = "Controla la velocidad con la que la APS (Amenaza Por Segundo) se actualiza.\nAumenta este valor para mejorar el funcionamiento, o ponlo a 0 para desactivar las entradas de APS"
L["Modules window"] = "Ventana de módulos"
L["Defaults"] = "Predeterminados"
L["Options that affect the appearance of all frames"] = "Opciones que afectan la apariencia de todos los marcos"
L["Reset to defaults"] = "Restaura valores predet."
L["Use global defaults for this frame"] = "Utiliza valores globales en este marco"
L["Show test bars"] = "Mostrar barras de prueba"
L["Test"] = "Prueba"

L["Modules"] = "Módulos"
L["Options for Omen's various modules"] = "Opciones para varios módulos del Omen"

L["Lock Omen"] = "Mostrar Omen"
L["Locks Omen in place and prevents it from being dragged or resized."] = "Muestra el Omen en una cierta posición y evita que se pueda mover o redimensionar"
L["Hide when not needed"] = "Esconder cuando no se necesite"

L["Animate bars"] = "Animar barras"
L["Smoothly animate bar changes"] = "Animar suavemente los cambios en las barras"
L["Hides Omen when you are resting, not in a party, or in an arena or battleground"] = "Esconder el Omen cuando descansas, no estas en grupo, en arena o en un campo de batalla"
L["Error"] = "Error"
L["Unable to use shake warning. If you have nameplates turned on, turn them off to enable shake warnings."] = "Incapaz de usar alarma con sacudida. Si tienes las placas con inscripción habilitadas, desactivalas para poder ver las alarmas con sacudida"

L["Background opacity"] = "Opacidad del fondo"
L["Opacity of each bar's background"] = "Opcidad de cada barra del fondo"
L["Background darkness"] = "Oscuridad del fondo"
L["Darkness of each bar's background"] = "Oscuridad de cada barra del fondo"

L["Opacity"] = "Opacidad"
L["Opacity of the entire frame"] = "Opacidad del marco entero"

L["Classes"] = "Clases"
L["DRUID"] = "Druida"
L["HUNTER"] = "Cazador"
L["MAGE"] = "Mago"
L["PALADIN"] = "Paladín"
L["PET"] = "Mascota"
L["PRIEST"] = "Sacerdote"
L["ROGUE"] = "Pícaro"
L["SHAMAN"] = "Chamán"
L["WARLOCK"] = "Brujo"
L["WARRIOR"] = "Guerrero"

L["Number of bars to show"] = "Número de barras a mostrar"
L["Autocollapse"] = "Auto-colapsar"
L["Collapse to show a minimum number of bars"] = "Colapsar para mostrar un número mínimo de barras"

L["Collapse hides bar list"] = "Colapsar esconde el listado de barras"
L["Let autocollapse hide the bar list if no bars are shown"] = "Permite a auto-colapsar esconder el listado de barras si no se muestra ninguna barra"
L["Collapse hides entire Omen window"] = "Colapsar esconde la ventana del Omen entera"
L["Let autocollapse hide the |c00ffffffentire window|r if no bars are shown. Note: This |c00ffffffwill|r prevent you from switching modules out of combat."] = "Permite a auto-colapsar esconder la |c00ffffffventana entera|r si no se muestra ninguna barra. Nota: Esto te |c00ffffffprevenirá|r de cambios bruscos en los módulos fuera de combate."

L["Grow Up"] = "Aumentar"
L["Grow bars upwards"] = "Aumentar las barras"
L["Toggle Omen"] = "Mostrar Omen"
L["Center Omen"] = "Centrar Omen"
L["Active when alone"] = "Activar cuando estas solo"
L["Enable ThreatLib even when you aren't in a party and don't have a pet."] = "Activar ThreatLib hasta cuando no estas en grupo o no tienes mascota"

L["Control the scale of the entire Omen GUI"] = "Controla la escala de todo el Omen"
L["Scale"] = "Escala"

L["Clamp to screen"] = "Fijar a la pantalla"
L["Clamp the Omen frame to the screen"] = "Fijar el marco del Omen a la pantalla"

L["Skin"] = "Piel"
L["Save your current settings and load other skins"] = "Guarda tus opciones actuales y carga otras pieles"
L["Load Skin..."] = "Carga piel..."
L["Load a saved skin"] = "Carga una piel guardada"
L["Save Skin As..."] = "Guardar piel como..."
L["Save the current settings as a skin"] = "Guardar las opciones actuales como una piel"

L["Click|r to toggle the Omen window"] = "Click|r para mostrar la ventana del Omen"
L["Right-click|r to open the options menu"] = "Click-dcho|r para abrir el menú de opciones"

L["Attach to minimap"] = "Adjuntar al minimapa"
L["FuBar options"] = "Opciones FuBarra"
L["Position"] = "Posición"
L["Left"] = "Izquierda"
L["Center"] = "Centro"
L["Right"] = "Derecha"
L["Show text"] = "Mostrar texto"
L["Show icon"] = "Mostrar icono"

L["Standby"] = "En espera"
L["Hide minimap/FuBar icon"] = "Esconder minimapa/FuBarra icono"

L["Configure Omen"] = "Configurar Omen"

L["Version Checks"] = "Comprobar versión"
L["Show all party member revisions"] = "Mostrar la versión de la gente del grupo"
L["Show oudated party member revisions"] = "Mostrar los miembros del grupo con versiones desactualizadas"

L["ThreatLib Version Check: All party members"] = "Comprobar versión de ThreatLib: Todos los miembros del grupo"
L["ThreatLib Version Check: Outdated party members"] = "Comprobar versión de ThreatLib: Miembros del grupo desactualizados"
L["latest is"] = "la último es"

L["You have a pet"] = "Tienes mascota"
L["Show Omen when you have a pet out"] = "Mostrar Omen cuando tienes la mascota fuera"
L["You are alone"] = "Estas solo"
L["Show Omen when you are alone"] = "Mostrar Omen cuando estas solo"
L["You are in a party"] = "Estas en grupo"
L["Show Omen when you are in a 5-man party"] = "Mostrar Omen cuando estas en un grupo de 5-pers"
L["You are in a raid"] = "Estas en banda"
L["Show Omen when you are in a raid"] = "Mostrar Omen cuando estas en una banda"
L["Show when..."] = "Mostrar cuando..."
L["Show Omen when..."] = "Mostrar Omen cuando..."
L["You are resting"] = "Estas descansando"
L["Show Omen when you are resting"] = "Mostrar Omen cuando estas descansando"
L["You are in a battleground"] = "Estas en un campo de batalla" 
L["Show Omen when you are in a battleground or arena"] = "Mostrar Omen cuando estas en un campo de batalla o en arena"
L["You are in a dungeon"] = "Estas en una mazmorra"
L["Show Omen when you are in a dungeon (5 man and raid)"] = "Mostrar Omen cuando estas en una mazmorra (grupo y banda)"

L["Unknown"] = "Desconocido"
L["Not compatible!"] = "¡No es compatible!"

L["Issue threat clear"] = "Tema de amenaza limpio"
L["Issue threat clear (requires party leader or raid assistant)"] = "Tema de amenaza limpio (requiere al lider del grupo o un asistente de banda)"

L["Your version of Omen/Threat is out of date. Please update from WAU or http://files.wowace.com/Omen/Omen.zip when possible."] = "Tu versión de Omen/Threat está desactualizado. Por favor actualizalo desde WAU o http://files.wowace.com/Omen/Omen.zip cuando puedas."
L["Your version of Omen/Threat is out of date and is not compatible with the newest version. You should update from WAU or http://files.wowace.com/Omen/Omen.zip as soon as possible."] = "Tu versión del Omen/Threat esta desactualizado e no es compatible con la versión mas nueva. Deberías actualizarlo desde WAU o http://files.wowace.com/Omen/Omen.zip lo antes posible."

L["Whisper older clients informing them to update."] = "Susurra a los clientes antiguos informandoles de que actualicen"
L["You must be the group leader or a group assistant to do this."] = "Debes ser el lider del grupo o un asistente de la banda para hacer esto"

BINDING_HEADER_OMEN = "Omen"
BINDING_NAME_OMENTOGGLE = "Mostrar Omen"
BINDING_NAME_OMENNEXTMODULE = "Ir al siguiente módulo"
BINDING_NAME_OMENPREVMODULE = "Ir al anterior módulo"

