local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Omen", "frFR")
if not L then return end
-- Initial translation courtesy of antarus
L["Background color"] = "Couleur arrière-plan"
L["Background texture"] = "Texture de l'arrière-plan"
L["Bar options"] = "Options des barres"
L["Border color"] = "Couleur de la bordure"
L["Border texture"] = "Texture de la bordure"
L["Color"] = "Couleur"
L["Configure"] = "Configurer"
L["Configure the labels that appear on the bars"] = "Configure les labels qui apparaissent sur les barres."
L["Control the label fonts"] = "Contrôle les polices d'écriture des labels."
L["Control the font size of the labels"] = "Contrôle la taille de la police des labels."
L["Display options"] = "Options d'affichage"
L["Font"] = "Police d'écriture"
L["Font settings"] = "Paramètres de la police"
L["Frame's border color"] = "Couleur de la bordure du cadre."
L["Height"] = "Hauteur"
L["Height of each bar"] = "Hauteur de chaque barre."
L["Labels"] = "Labels"
L["Window options"] = "Options de la fenêtre"
L["None"] = "Aucun"
L["Open the configuration dialog"] = "Ouvre le panneau de configuration."
L["Options that control Omen's appearance"] = "Options contrôlant l'apparence de Omen."
L["Options for modifying the look and feel of the main display"] = "Options modifiant l'affichage principal."
L["Options which affect the style of the threat bars"] = "Options affectant le style des barres de menace."
L["Outline"] = "Contour"
L["Size"] = "Taille"
L["Control the size of this frame"] = "Contrôle la taille de ce cadre."
L["Spacing"] = "Espacement"
L["Spacing between each bar"] = "Espacement entre chaque barre."
L["Stretch textures"] = "Déformer les textures"
L["Stretch textures to fit the width of the bar"] = "Déforme les textures afin qu'elles s'adaptent à la longeur des barres."
L["Texture"] = "Texture"
L["Thick Outline"] = "Contour épais"
L["The color of the labels"] = "La couleur des labels."
L["The font that the labels will use"] = "La police d'écriture que les labels utiliseront."
L["The outline that the labels will use"] = "Le contour que les labels utiliseront."
L["The texture that the bar will use"] = "La texture que les barres utiliseront."

L["Texture to use for the frame's background"] = "Texture à utiliser pour l'arrière-plan du cadre."
L["Texture to use for the frame's border"] = "Texture à utiliser pour la bordure du cadre."
L["Main display's border color"] = "Couleur de la bordure de l'affichage principal."
L["Bars window"] = "Cadre des barres"
L["Options that affect the appearance of the bar list window"] = "Options affectant l'apparence du cadre de la liste des barres."
L["Options that affect the appearance of the title window"] = "Options affectant l'apparence du cadre du titre."
L["Options that affect the appearance of the module list window"] = "Options affectant l'apparence du cadre de la liste des modules."
L["Title window"] = "Cadre du titre"
L["Hide version"] = "Masquer la version"
L["Hide the version number and out-of-date notice"] = "Masque le numéro de version et l'indicateur de péremption."
L["Hide"] = "Masquer"
L["Hide this frame"] = "Masque ce cadre."
L["Options not related to appearance"] = "Options ne concernant pas l'apparence."
L["General options"] = "Options générales"
L["TPS Update Frequency"] = "Fréquence des MÀJ de la MPS"
L["Controls the speed at which TPS (threat per second) values update.\nRaise this value to increase performance, or set it to 0 to turn off TPS queries."] = "Contrôle la vitesse à laquelle les valeurs de la MPS (menace par seconde) sont mises à jour.\nAugmenter cette valeur pour améliorer les performances, ou mettez-la à 0 pour désactiver les requêtes MPS."
L["Modules window"] = "Cadre des modules"
L["Defaults"] = "Défauts"
L["Options that affect the appearance of all frames"] = "Options affectant l'apparence de tous les cadres."
L["Reset to defaults"] = "Réinitialiser"
L["Use global defaults for this frame"] = "Utilise les paramètres globaux par défaut pour ce cadre."
L["Show test bars"] = "Barres de test"
L["Test"] = "Test"

L["Modules"] = "Modules"
L["Options for Omen's various modules"] = "Options concernant les divers modules de Omen."

L["Lock Omen"] = "Verrouiller Omen"
L["Locks Omen in place and prevents it from being dragged or resized."] = "Verrouille la fenêtre de Omen à sa position actuelle afin d'éviter qu'elle ne soit déplacée ou redimensionnée."
L["Hide when not needed"] = " Masquer si inutile"

L["Animate bars"] = "Animer les barres"
L["Smoothly animate bar changes"] = "Anime de manière fluide les changements dans les barres."
L["Hides Omen when you are resting, not in a party, or in an arena or battleground"] = "Masque Omen quand vous vous reposez, quand vous n'êtes pas dans un groupe, ou quand vous êtes en arène on dans un champ de bataille."
L["Error"] = "Erreur"
L["Unable to use shake warning. If you have nameplates turned on, turn them off to enable shake warnings."] = "Impossible d'utiliser les avertissements par secousse."

L["Background opacity"] = "Opacité de l'arrière-plan"
L["Opacity of each bar's background"] = "Opacité de l'arrière-plan de chaque barre."
L["Background darkness"] = "Obscurité de l'arrière-plan"
L["Darkness of each bar's background"] = "Obscurité de l'arrière-plan de chaque barre."

L["Opacity"] = "Opacité"
L["Opacity of the entire frame"] = "Opacité de tout le cadre."

L["Classes"] = "Classes"
L["DRUID"] = "Druide"
L["HUNTER"] = "Chasseur"
L["MAGE"] = "Mage"
L["PALADIN"] = "Paladin"
L["PET"] = "Familier"
L["PRIEST"] = "Prêtre"
L["ROGUE"] = "Voleur"
L["SHAMAN"] = "Chaman"
L["WARLOCK"] = "Démoniste"
L["WARRIOR"] = "Guerrier"

L["Number of bars to show"] = "Nbre de barres à afficher"
L["Autocollapse"] = "Réduire auto."
L["Collapse to show a minimum number of bars"] = "Réduit afin d'afficher un nombre minimal de barres."

L["Collapse hides bar list"] = "Réduire masque la liste des barres"
L["Let autocollapse hide the bar list if no bars are shown"] = "Permet à la réduction auto. de masquer la liste des barres si aucune barre n'est affichée."
L["Collapse hides entire Omen window"] = "Réduire masque toute la fenêtre"
L["Let autocollapse hide the |c00ffffffentire window|r if no bars are shown. Note: This |c00ffffffwill|r prevent you from switching modules out of combat."] = "Permet à la réduction auto. de masquer |c00fffffftoute la fenêtre|r si aucune barre d'est affichée. Note : Ceci |c00ffffffvous empêchera|r de changer de modules hors combat."

L["Grow Up"] = "Vers le haut"
L["Grow bars upwards"] = "Ajoute les barres vers le haut."
L["Toggle Omen"] = "Afficher/masquer Omen"
L["Center Omen"] = "Centrer Omen"
L["Active when alone"] = "Activer quand seul"
L["Enable ThreatLib even when you aren't in a party and don't have a pet."] = "Active ThreatLib même si vous n'êtes pas dans un groupe et même si vous n'avez pas de familier."

L["Control the scale of the entire Omen GUI"] = "Contrôle l'échelle de la totalité du GUI de Omen."
L["Scale"] = "Échelle"

L["Clamp to screen"] = "Garder à l'écran"
L["Clamp the Omen frame to the screen"] = "Garde le cadre de Omen à l'écran."

L["Skin"] = "Skin"
L["Save your current settings and load other skins"] = "Sauvegarde vos paramètres actuels et charge d'autres skins."
L["Load Skin..."] = "Charger skin..."
L["Load a saved skin"] = "Charge un skin sauvegardé."
L["Save Skin As..."] = "Sauver le skin sous..."
L["Save the current settings as a skin"] = "Sauvegarde les paramètres actuels dans un skin."

L["Click|r to toggle the Omen window"] = "Cliquez|r pour afficher/masquer la fenêtre de Omen."
L["Right-click|r to open the options menu"] = "Clic-droit|r pour ouvrir le menu des options."

L["Attach to minimap"] = "Attacher à la minicarte"
L["FuBar options"] = "Options FuBar"
L["Position"] = "Position"
L["Left"] = "Gauche"
L["Center"] = "Centre"
L["Right"] = "Droite"
L["Show text"] = "Afficher le texte"
L["Show icon"] = "Afficher l'icône"

L["Standby"] = "Veille"
L["Hide minimap/FuBar icon"] = "Masquer l'icône"

L["Configure Omen"] = "Configurer Omen"

L["Version Checks"] = "Vérif. des versions"
L["Show all party member revisions"] = "Versions des membres"
L["Show oudated party member revisions"] = "Versions périmées"

L["ThreatLib Version Check: All party members"] = "Vérification ThreatLib : Versions de tous les membres"
L["ThreatLib Version Check: Outdated party members"] = "Vérification ThreatLib : Versions périmées"
L["latest is"] = "dernière :"

L["You have a pet"] = "Vous avez un familier"
L["Show Omen when you have a pet out"] = "Affiche Omen quand votre familier est à vos côtés."
L["You are alone"] = "Vous êtes seul"
L["Show Omen when you are alone"] = "Affiche Omen quand vous êtes tout seul."
L["You are in a party"] = "Vous êtes en groupe"
L["Show Omen when you are in a 5-man party"] = "Affiche Omen quand vous êtes dans un groupe de 5 personnes au maximum."
L["You are in a raid"] = "Vous êtes en raid"
L["Show Omen when you are in a raid"] = "Affiche Omen quand vous êtes dans un raid."
L["Show when..."] = "Afficher quand..."
L["Show Omen when..."] = "Affiche Omen quand..."
L["You are resting"] = "Vous êtes en repos"
L["Show Omen when you are resting"] = "Affiche Omen quand vous êtes entrain de vous reposer."
L["You are in a battleground"] = "Vous êtes dans un CdB"
L["Show Omen when you are in a battleground or arena"] = "Affiche Omen quand vous êtes dans un champ de bataille ou dans une arène."
L["You are in a dungeon"] = "Vous êtes en donjon"
L["Show Omen when you are in a dungeon (5 man and raid)"] = "Affiche Omen quand vous êtes dans un donjon (à 5 joueurs et en raid)."

L["Unknown"] = "Inconnu"
L["Not compatible!"] = "Incompatible !"

L["Issue threat clear"] = "RÀZ des menaces"
L["Issue threat clear (requires party leader or raid assistant)"] = "Effectue une réinitialisation des menaces (nécessite d'être le chef du groupe ou assistant)."

L["Your version of Omen/Threat is out of date. Please update from WAU or http://files.wowace.com/Omen/Omen.zip when possible."] = "Votre version de Omen/Threat est périmée. Veuillez vous mettre à jour via le WAU ou via http://files.wowace.com/Omen/Omen.zip quand vous aurez le temps."
L["Your version of Omen/Threat is out of date and is not compatible with the newest version. You should update from WAU or http://files.wowace.com/Omen/Omen.zip as soon as possible."] = "Votre version de Omen/Threat est périmée et incompatible avec la version la plus récente. Veuillez vous mettre à jour via le WAU ou via http://files.wowace.com/Omen/Omen.zip le plus vite possible."

L["Whisper older clients informing them to update."] = "Prévenir les périmés"
L["You must be the group leader or a group assistant to do this."] = "Vous devez être le chef du groupe ou assistant pour faire cela."

BINDING_HEADER_OMEN = "Omen"
BINDING_NAME_OMENTOGGLE = "Afficher/masquer Omen"
BINDING_NAME_OMENNEXTMODULE = "Aller au module suivant"
BINDING_NAME_OMENPREVMODULE = "Aller au module précédent"
