--  Translation by Eritnull (StingerSoft aka Шептун)
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Omen", "ruRU")
if not L then return end

L["Background color"] = "Цвет фона"
L["Background texture"] = "Текстура фона"
L["Bar options"] = "Опции полос"
L["Border color"] = "Цвет полей"
L["Border texture"] = "Текстура полей"
L["Color"] = "Цвет"
L["Configure"] = "Настройки"
L["Configure the labels that appear on the bars"] = "Настройка надписей которые будут на полосах"
L["Control the label fonts"] = "Настройка шрифта надписей"
L["Control the font size of the labels"] = "Настройка размера шрифта надписей"
L["Display options"] = "Опции отображения"
L["Font"] = "Шрифт"
L["Font settings"] = "Настройки Шрифта"
L["Frame's border color"] = "Цвет фреймов полей"
L["Height"] = "Высота"
L["Height of each bar"] = "Высота каждой полосы"
L["Labels"] = "Надписи"
L["Window options"] = "Опции окна"
L["None"] = "Ни чего"
L["Open the configuration dialog"] = "Открыть диалог конфигурации"
L["Options that control Omen's appearance"] = "Настройка внешнего вида Omen'а"
L["Options for modifying the look and feel of the main display"] = "Настройки отображения заглавного окна"
L["Options which affect the style of the threat bars"] = "Настройки стилей полос угрозы"
L["Outline"] = "Контур"
L["Size"] = "Размер"
L["Control the size of this frame"] = "Размер фрейма"
L["Spacing"] = "Расстояние"
L["Spacing between each bar"] = "Расстояние между полосами"
L["Stretch textures"] = "Текстуры полос"
L["Stretch textures to fit the width of the bar"] = "Текстуры соответствующие ширине полос"
L["Texture"] = "Текстуры" 
L["Thick Outline"] = "Толстый контур"
L["The color of the labels"] = "Цвет меток"
L["The font that the labels will use"] = "Шрифт меток"
L["The outline that the labels will use"] = "Контур меток"
L["The texture that the bar will use"] = "Текстура полос"

L["Texture to use for the frame's background"] = "Текстура фона фреймов"
L["Texture to use for the frame's border"] = "Текстура полей фреймов"
L["Main display's border color"] = "Цвет полей заглавного окна"
L["Bars window"] = "Полосы окна"
L["Options that affect the appearance of the bar list window"] = "Опции появления списка полос в окне"
L["Options that affect the appearance of the title window"] = "Опции появления заглавного окна"
L["Options that affect the appearance of the module list window"] = "Опции появления списка окна модуля"
L["Title window"] = "Заглавие окна"
L["Hide version"] = "Скрыть версию"
L["Hide the version number and out-of-date notice"] = "Скрыть версию и уведомление о старой версии"
L["Hide"] = "Скрыть"
L["Hide this frame"] = "Скрыть этот фрейм"
L["Options not related to appearance"] = "Опции не связанные с появлением"
L["General options"] = "Общие настройки"
L["TPS Update Frequency"] = "Частота обновлений TPS"
L["Controls the speed at which TPS (threat per second) values update.\nRaise this value to increase performance, or set it to 0 to turn off TPS queries."] = "Регулирует с кокой скоростью будет обновляться значение TPS (угрозы за секунду).\nПоднимая это значение возрастает производительность, или установите значение на 0 чтобы отключить запрос TPS."
L["Modules window"] = "Модули окна"
L["Defaults"] = "По умолчанию"
L["Options that affect the appearance of all frames"] = "Опции внешнего вида всех фреймов"
L["Reset to defaults"] = "Сброс на по умолчанию"
L["Use global defaults for this frame"] = "Использовать общие настройки для фреймов"
L["Show test bars"] = "Показать тест полосы"
L["Test"] = "Тест"

L["Modules"] = "Модули"
L["Options for Omen's various modules"] = "Опции для различных модулей Omenа"

L["Lock Omen"] = "Закрепить"
L["Locks Omen in place and prevents it from being dragged or resized."] = "Закрепить Omen на своём месте. Это препятствует передвижению и изменению размера"
L["Hide when not needed"] = "Скрыть если не нужен"

L["Animate bars"] = "Анимация полос"
L["Smoothly animate bar changes"] = "Плавная анимация изменений полос"
L["Hides Omen when you are resting, not in a party, or in an arena or battleground"] = "Скрыть Omen когда вы отдыхаете, не в группе, или на арене,поле сражений"
L["Error"] = "Ошибка"
L["Unable to use shake warning. If you have nameplates turned on, turn them off to enable shake warnings."] = "Невозможно использовать предупреждение встряской. Если вы включили именную табличку, отключите её для включения предупреждений встряской"

L["Background opacity"] = "Полупрозрачность фона"
L["Opacity of each bar's background"] = "Полупрозрачность фона полос"
L["Background darkness"] = "Темнота фона"
L["Darkness of each bar's background"] = "Темнота фона полос"

L["Opacity"] = "Полупрозрачность"
L["Opacity of the entire frame"] = "Полупрозрачность всего фрейма"

L["Classes"] = "Классы"
L["DRUID"] = "Друид"
L["HUNTER"] = "Охотник"
L["MAGE"] = "Маг"
L["PALADIN"] = "Паладин"
L["PET"] = "Питомец"
L["PRIEST"] = "Жрец"
L["ROGUE"] = "Разбойник"
L["SHAMAN"] = "Шаман"
L["WARLOCK"] = "Чернокнижник"
L["WARRIOR"] = "Воин"

L["Number of bars to show"] = "Число показываемых полос"
L["Autocollapse"] = "Авто-сворачивание"
L["Collapse to show a minimum number of bars"] = true

L["Collapse hides bar list"] = "Сворачивать список полос"
L["Let autocollapse hide the bar list if no bars are shown"] = "Авто-сворачивать список полос если нет активных полос"
L["Collapse hides entire Omen window"] = true
L["Let autocollapse hide the |c00ffffffentire window|r if no bars are shown. Note: This |c00ffffffwill|r prevent you from switching modules out of combat."] = true

L["Grow Up"] = "Рост вверх"
L["Grow bars upwards"] = "Возрастание полос вверх"
L["Toggle Omen"] = "Переключатель Omen'а"
L["Center Omen"] = "Центр Omen'а"
L["Active when alone"] = "Активен когда один"
L["Enable ThreatLib even when you aren't in a party and don't have a pet."] = "Включить ThreatLib когда вы не в группе/рейде и без питомца"

L["Control the scale of the entire Omen GUI"] = "Изменение размера окна Omen'а"
L["Scale"] = "Масштаб"

L["Clamp to screen"] = "Фиксировать на экране"
L["Clamp the Omen frame to the screen"] = "Фиксирует фрейм Omen'а на экране"

L["Skin"] = "Шкурка"
L["Save your current settings and load other skins"] = "Сохранить ваши текущие параметры и загрузить другую шкурку"
L["Load Skin..."] = "Загрузить Шкурку.."
L["Load a saved skin"] = "Загрузить сохраненную шкурку"
L["Save Skin As..."] = "Сохранить Шкурку как.."
L["Save the current settings as a skin"] = "Сохраните текущие параметры как шкурку"

L["Click|r to toggle the Omen window"] = "Кликни|r чтоб открыть-закрыть окно Omen'а"
L["Right-click|r to open the options menu"] = "Правый-Клик|r чтоб открыть меню настроек"

L["Attach to minimap"] = "Прикрепить к МиниКарте"
L["FuBar options"] = "Опции FuBar'а"
L["Position"] = "Расположение"
L["Left"] = "С лева"
L["Center"] = "Центр"
L["Right"] = "С право"
L["Show text"] = "Показать текст"
L["Show icon"] = "Показать икону"

L["Standby"] = "В режиме ожидания"
L["Hide minimap/FuBar icon"] = "Скрыть икону у МиниКарты/FuBar'а"

L["Configure Omen"] = "Настройка Omen'а"

L["Version Checks"] = "Проверка версии"
L["Show all party member revisions"] = "Показать ревизии всех участников группы"
L["Show oudated party member revisions"] = "Показать устаревшие ревизии участников группы"

L["ThreatLib Version Check: All party members"] = "Проверка Версии ThreatLib: Все игроки группы"
L["ThreatLib Version Check: Outdated party members"] = "Проверка Версии ThreatLib: Устаревшая у игроков группы"
L["latest is"] = "последняя"

L["You have a pet"] = "Вы с питомцем"
L["Show Omen when you have a pet out"] = "Показать Omen когда вы с питомцем"
L["You are alone"] = "Вы один"
L["Show Omen when you are alone"] = "Показать Omen когда вы один"
L["You are in a party"] = "Вы в группе"
L["Show Omen when you are in a 5-man party"] = "Показать Omen когда вы находитесь в группе"
L["You are in a raid"] = "Вы в рейде"
L["Show Omen when you are in a raid"] = "Показать Omen когда вы находитесь в рейде"
L["Show when..."] = "Показать когда..."
L["Show Omen when..."] = "Показать Omen когда..."
L["You are resting"] = "Вы отдыхаете"
L["Show Omen when you are resting"] = "Показать Omen когда вы отдыхаете"
L["You are in a battleground"] = "Вы на поле сражения" 
L["Show Omen when you are in a battleground or arena"] = "Показать Omen когда вы на поле сражения или арене"
L["You are in a dungeon"] = "Вы в подземелье"
L["Show Omen when you are in a dungeon (5 man and raid)"] = "Показать Omen когда вы находитесь в подземелье (5 чел и рейде)"

L["Unknown"] = "Неизвестно"
L["Not compatible!"] = "Не совместим!"

L["Issue threat clear"] = "Очистить список угроз"
L["Issue threat clear (requires party leader or raid assistant)"] = "Очистить список угроз (Требуется лидер группы или ассистент)"

L["Your version of Omen/Threat is out of date. Please update from WAU or http://files.wowace.com/Omen/Omen.zip when possible."] = "Ваша версия Omen'а/Threat'а устарела. Пожалуйста обновите через WAU или скачайте с http://files.wowace.com/Omen/Omen.zip если возможно."
L["Your version of Omen/Threat is out of date and is not compatible with the newest version. You should update from WAU or http://files.wowace.com/Omen/Omen.zip as soon as possible."] = "Ваша версия Omen'а/Threat'а устарела и не совместима с более новыми версиями. Вы должны обновить через WAU или скачать с http://files.wowace.com/Omen/Omen.zip как можно быстрее."

L["Whisper older clients informing them to update."] = "Шепнуть информирование о обновлении устаревшим клиентам"
L["You must be the group leader or a group assistant to do this."] = "Вы должны быть лидером группы или ассистентом чтобы сделать это."

BINDING_HEADER_OMEN = "Omen"
BINDING_NAME_OMENTOGGLE = "Переключатель Omena"
BINDING_NAME_OMENNEXTMODULE = "Следующий модуль"
BINDING_NAME_OMENPREVMODULE = "Предыдущий модуль"

