StatusWindowOptions.strings = {
	SCALE = "Scale (%.01f)",
	OPACITY = "Transparency (%.02f)",
	WIDTH = "Width (%d)",
	HEIGHT = "Height (%d)",
	FONTSIZE = "Font size (%d)",
  BORDERSIZE = "Border size (%d)",
  ROWCOUNT = "Frames in row (%d)",
  FONT = "Font",
	FRAMES = "Frames",
	BORDER = "Border",
	BACKGROUND = "Background",
	WINDOW = "Window ",
	BORDERCOLOUR = "Border Colour",
	TEXTCOLOUR = "Text Colour",
	BGCOLOUR = "Background Colour",
	UP = "Up",
	DOWN = "Down",
	REMOVE = "Remove",
	ADD = "Add",
	PANETITLE = "Window %d / Frame %d",
	MODULE = "Module",
  NONE = "None",
  USEWINDOWCOLOUR = "Always use window colour",
  USEWINDOWCOLOURTT1 = "When selected, the window font colour will override",
  USEWINDOWCOLOURTT2 = "any specific text colouring the module may use",
  ICONFIRST = "StatusWindow only supports $i at the beginning of a label at this time",
  NOICON = "Module %s does not have an icon",
  RESETPROFILE = "This will clear all settings for the current profile!",
  RESETBUTTON = "Reset Profile",
  NEWWINDOW = "New Window",
  REMOVEWINDOW = "Remove Window",
  COPYPROFILE = "Copy Profile",
  
  -- Generic config frame strings
  PADDING = "Padding (%d)",
  ALIGN = "Text alignment",
}
