--$Id: deDE.lua 35960 2007-05-20 16:11:20Z gamefaq $-- 
-- deDE localization by Gamefaq
local L = AceLibrary("AceLocale-2.2"):new("OneBag")
L:RegisterTranslations("deDE", function()
   return {
      ["Frame"]	= "Fenster",
      ["Frame Options"]	= "Fensteroptionen.",
      ["Columns"]	= "Spalten",
      ["Sets the number of columns to use"]	= "Stellt die Spaltenzahl ein.",
      ["Scale"]	= "Skalierung",
      ["Sets the scale of the frame"]	= "Stellt die Größe des Fensters ein.",
      ["Strata"]	= "Schichten",
      ["Sets the strata of the frame"]	= "Stellt die Schichthöhe des Fensters ein, wodurch das überlagern dieses Fensters mit einem anderen verhindert werden kann.",
      ["Alpha"]	= "Transparenz",
      ["Sets the alpha of the frame"]	= "Stellt die Transparenz des Fensters ein.",
      ["Locked"]	= "Fixieren",
      ["Toggles the ability to move the frame"]	= "Bestimmt, ob das Fenster verschoben werden kann.",
      ["Clamped"]	= "Sichtbereich",
      ["Toggles the ability to drag the frame off screen."]	= "Verhindert, dass das Fenster außerhalb des sichtbaren Bereichs geschoben wird.",
      ["Bag Break"] = "Taschen in neuer Zeile",
      ["Sets wether to start a new row at the beginning of a bag."] = "Die Anzeige jeder Tasche in einer neuen Zeile beginnen.",
      ["Vertical Alignment"] = "Vertikale Ausrichtung",
      ["Sets wether to have the extra spaces on the top or bottom."] = "Freie Taschenplätze oben oder unten anzeigen.",
      ["Top"] = "Oben",
      ["Bottom"] = "Unten",

      ["Show"]	= "Zeige",
      ["Various Display Options"]	= "Verschiedene Anzeigeoptionen.",
      ["Counts"]	= "Anzahl",
      ["Toggles showing the counts for special bags."]	= "Anzahl freier Plätze in den Spezialtaschen anzeigen.",
      ["Direction"]	= "Richtung",
      ["Forward"]	= "Vorwärts",
      ["Toggles direction the bags are shown"]	= "Bestimmt die Richtung, in der die Taschen angezeigt werden.",
      ["|cffff0000Reverse|r"]	= "|cffff0000Rückwärts|r",
      ["|cff00ff00Forward|r"]	= "|cffff0000Vorwärts|r",
      ["Ammo Bag"]	= "Munitionstaschen",
      ["Turns display of ammo bags on and off."]	= "Schaltet die Munitionstaschen an und aus.",
      ["Soul Bag"]	= "Seelentaschen",
      ["Turns display of soul bags on and off."]	= "Schaltet die Seelentaschen an und aus.",
      ["Profession Bag"]	= "Berufe-Taschen",
      ["Turns display of profession bags on and off."]	= "Schaltet die Berufe-Taschen an und aus.",
      ["Backpack"] = "Rucksack",
      ["Turns display of your backpack on and off."] = "Schaltet den Rucksack an und aus.",
      ["First Bag"] = "Erste Tasche",
      ["Turns display of your first bag on and off."] = "Schaltet die Anzeige der ersten Tasche an und aus.",
      ["Second Bag"] = "Zweite Tasche",
      ["Turns display of your second bag on and off."] = "Schaltet die Anzeige der zweiten Tasche an und aus.",
      ["Third Bag"] = "Dritte Tasche",
      ["Turns display of your third bag on and off."] = "Schaltet die Anzeige der dritten Tasche an und aus.",
      ["Fourth Bag"] = "Vierte Tasche",
      ["Turns display of your fourth bag on and off."] = "Schaltet die Anzeige der vierte Tasche an und aus.",
      ["'s Bags"] = "'s Taschen",		

      ["Colors"]	= "Farben",
      ["Different color code settings."]	= "Verschiedene Farbeinstellungen.",
      ["Mouseover Color"]	= "Hervorhebungsfarbe",
      ["Changes the highlight color for when you mouseover a bag slot."]	= "Verändert die Farbe, in der Taschenplätze hervorgehoben werden, wenn du mit dem Mauszeiger darauf zeigst.",
      ["Ammo Bag Color"]	= "Farbe der Munitionstaschen",
      ["Changes the highlight color for Ammo Bags."]	= "Verändert die Hervorhebungsfarbe für Munitionstaschen.",
      ["Soul Bag Color"]	= "Farbe der Seelentaschen",
      ["Changes the highlight color for Soul Bags."]	= "Verändert die Hervorhebungsfarbe für Seelentaschen.",
      ["Profession Bag Color"]	= "Farbe der Berufe-Taschen",
      ["Changes the highlight color for Profession Bags."]	= "Verändert die Hervorhebungsfarbe für Berufe-Taschen.",
      ["Background Color"]	= "Hintergrundfarbe",
      ["Changes the background color for the frame."]	= "Verändert die Hintergrundfarbe des Fensters.",
      ["Highlight Glow"]	= "Hervorhebungsleuchten",
      ["Turns hightlight glow on and off."]	= "Schaltet das Hervorhebungsleuchten an und aus.",
      ["Rarity Coloring"]	= "Einfärbung nach Seltenheit",
      ["Turns rarity coloring on and off."]	= "Schaltet die Seltenheitseinfärbung (z.B. violett für episch) von Gegenständen an und aus.",

      ["Reset"]	= "Zurücksetzen",
      ["Reset the different colors."]	= "Setzt die Farbeinstellungen auf die Standardwerte zurück.",
      ["Mouseover Color"]	= "Hervorhebungsfarbe",
      ["Returns your mouseover color to the default."]	= "Setzt die Hervorhebungsfarbe auf die Grundeinstellung zurück.",
      ["Ammo Slot Color"]	= "Munitionsplätze",
      ["Returns your ammo slot color to the default."]	= "Setzt die Farbe der Munitionsplätze auf die Grundeinstellung zurück.",
      ["Soul Slot Color"]	= "Seelensteinplätze",
      ["Returns your soul slot color to the default."]	= "Setzt die Farbe der Seelensteinplätze auf die Grundeinstellung zurück.",
      ["Profession Slot Color"]	= "Berufe-Plätze",
      ["Returns your profession slot color to the default."]	= "Setzt die Farbe der Berufe-Plätze auf die Grundeinstellung zurück.",
      ["Background"]	= "Hintergrund",
      ["Returns your frame background to the default."]	= "Setzt die Hintergrundfarbe auf die Grundeinstellung zurück.",
      ["Plow!"]	= "Plow!",
      ["Organizes your bags."]	= "Sortiert deine Taschen.",
      ["- Note: This option only appears if you have MrPlow installed"]	= "- Hinweis: Diese Option erscheint nur wenn du das Addon MrPlow installiert hast.",

      ["Pick Locale"] = "Spache auswählen", 
      ["Sets the locale to use.  Will not take effect until you reload your UI."] = "Stellt die zu benutzende Sprachs ein. \195\132nderungen werden erst nach dem Neuladen des Interface aktiv.",

      ["%s ran in %s"]	= "%s benötigte %s",
      ["Checking if bag %s is open"]	= "Prüfe, ob Tasche %s geöffnet ist.",
      ["Opening bag %s"]	= "Öffne Tasche %s",
      ["Closing bag %s"]	= "Schließe Tasche %s",

      ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "Plätze belegt: %s, Seelensteine: %s, Berufe-Plätze belegt: %s, Munitionsplätze belegt: %s, %s Schuss.",
      ["%s/%s Slots"]	= "%s/%s Plätze",
      ["%s/%s Ammo"]	= "%s/%s Schuss",
      ["%s/%s Soul Shards"]	= "%s/%s Seelensplitter",
      ["%s/%s Profession Slots"]	= "%s/%s Berufe-Plätze",
      
      ["Menu"] = "Menü" 
   }
end)