--$Id: frFR.lua 39863 2007-06-14 13:06:35Z pettigrow $-- 
local L = AceLibrary("AceLocale-2.2"):new("OneBag")

L:RegisterTranslations("frFR", function() return {
	["Frame"] = "Fenêtre",
	["Frame Options"] = "Options concernant la fenêtre pricipale.",
	["Columns"] = "Colonnes",
	["Sets the number of columns to use"] = "Détermine le nombre de colonnes à utiliser.",
	["Scale"] = "Echelle",
	["Sets the scale of the frame"] = "Détermine l'échelle de la fenêtre.",
	["Strata"] = "Couche",
	["Sets the strata of the frame"] = "Détermine la couche de la fenêtre.",
	["Alpha"] = "Transparence",
	["Sets the alpha of the frame"] = "Détermine la transparence de la fenêtre.",
	["Locked"] = "Verrouiller",
	["Toggles the ability to move the frame"] = "Permet ou non de déplacer la fenêtre.",
	["Clamped"] = "Clamp",
	["Toggles the ability to drag the frame off screen."] = "Permet ou non de sortir la fenêtre de l'écran.",
	["Bag Break"] = "Séparation des sacs",
	["Sets wether to start a new row at the beginning of a bag."] = "Commence ou non une nouvelle ligne au début d'un sac.",
	["Vertical Alignment"] = "Alignement vertical",
	["Sets wether to have the extra spaces on the top or bottom."] = "Détermine si les espaces supplémentaires sont en haut ou en bas.",
	["Top"] = "Haut",
	["Bottom"] = "Bas",

	["Show"] = "Affichage",
	["Various Display Options"] = "Options diverses concernant l'affichage.",
	["Counts"] = "Compteur",
	["Toggles showing the counts for special bags."]  = "Affiche ou non le compteur pour les sacs spéciaux.",
	["Direction"] = "Direction",
	["Forward"] = "En avant",
	["Toggles direction the bags are shown"] = "Détermine la direction vers laquelle les sacs sont affichés.",
	["|cffff0000Reverse|r"] = "|cffff0000Inverser|r",
	["|cff00ff00Forward|r"] = "|cff00ff00En avant|r",
	["Ammo Bag"] = "Sac de munitions",
	["Turns display of ammo bags on and off."] = "Affiche ou non les emplacements du sac de munitions.",
	["Soul Bag"] = "Sac d'âme",
	["Turns display of soul bags on and off."] = "Affiche ou non les emplacements du sac d'âme.",
	["Profession Bag"] = "Sac de profession",
	["Turns display of profession bags on and off."] = "Affiche ou non les emplacements du sac de profession.",
	["Backpack"] = "Sac à dos",
	["Turns display of your backpack on and off."] = "Affiche ou non les emplacements du sac à dos.",
	["First Bag"] = "Sac 1",
	["Turns display of your first bag on and off."] = "Affiche ou non les emplacements du premier sac.",
	["Second Bag"] = "Sac 2",
	["Turns display of your second bag on and off."] = "Affiche ou non les emplacements du second sac.",
	["Third Bag"] = "Sac 3",
	["Turns display of your third bag on and off."] = "Affiche ou non les emplacements du troisème sac.",
	["Fourth Bag"] = "Sac 4",
	["Turns display of your fourth bag on and off."] = "Affiche ou non les emplacements du quatrième sac.",
	["'s Bags"] = " : Inventaire",

	["Colors"] = "Couleurs",
	["Different color code settings."] = "Paramètres des différents codes couleur.",
	["Mouseover Color"] = "Couleur au passage de la souris",
	["Changes the highlight color for when you mouseover a bag slot."] = "Modifie la couleur de mise en évidence quand vous passez votre souris sur un emplacement.",
	["Ammo Bag Color"] = "Couleur du sac de munitions",
	["Changes the highlight color for Ammo Bags."] = "Modifie la couleur de mise en évidence du sac de munitions.",
	["Soul Bag Color"] = "Couleur du sac d'âme",
	["Changes the highlight color for Soul Bags."] = "Modifie la couleur de mise en évidence du sac d'âme.",
	["Profession Bag Color"] = "Couleur du sac de profession",
	["Changes the highlight color for Profession Bags."] = "Modifie la couleur de mise en évidence du sac de profession.",
	["Background Color"] = "Couleur de l'arrière-plan",
	["Changes the background color for the frame."]   = "Modifie la couleur de l'arrière-plan de la fenêtre.",
	["Highlight Glow"] = "Effet lumineux",
	["Turns hightlight glow on and off."] = "Active ou non l'effet lumineux des cadres.",
	["Rarity Coloring"] = "Coloration selon la rareté",
	["Turns rarity coloring on and off."] = "Colore ou non les objets selon la rareté.",

	["Reset"] = "RÀZ",
	["Reset the different colors."] = "Réinitialise les différentes couleurs.",
	["Mouseover Color"] = "Couleur au passage de la souris",
	["Returns your mouseover color to the default."] = "Réutilise la valeur par défaut de la couleur au passage de la souris.",
	["Ammo Slot Color"] = "Couleur des emplacements des munitions",
	["Returns your ammo slot color to the default."] = "Réutilise la valeur par défaut de la couleur des emplacements des munitions.",
	["Soul Slot Color"] = "Couleur des emplacements des fragments",
	["Returns your soul slot color to the default."] = "Réutilise la valeur par défaut de la couleur des emplacements des fragments.",
	["Profession Slot Color"] = "Couleur des emplacements de profession",
	["Returns your profession slot color to the default."] = "Réutilise la valeur par défaut de la couleur des emplacements de profession.",
	["Background"] = "Arrière-plan",
	["Returns your frame background to the default."] = "Réutilise la valeur par défaut de la couleur de l'arrière-plan.",
	["Plow!"] = "Plow!",
	["Organizes your bags."]  = "Réorganise vos sacs.",
	["- Note: This option only appears if you have MrPlow installed"] = "- Note: cette option n'apparaît que si vous avez installé MrPlow.",

	["Pick Locale"] = "Choix de la langue",
	["Sets the locale to use.  Will not take effect until you reload your UI."] = "Détermine la langue à utiliser. Ne prendra pas effet tant que vous n'avez pas recharger votre IU.",

	["%s ran in %s"] = "%s effectué en %s",
	["Checking if bag %s is open"] = "Vérification si le sac %s est ouvert",
	["Opening bag %s"] = "Ouverture du sac %s",
	["Closing bag %s"] = "Fermeture du sac %s",

	["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."] = "Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s.",
	["%s/%s Slots"] = "%s/%s places",
	["%s/%s Ammo"] = "%s/%s munitions",
	["%s/%s Soul Shards"] = "%s/%s fragments",
	["%s/%s Profession Slots"] = "%s/%s de profession",

	["Menu"] = "Menu"
}
end)