local L = AceLibrary("AceLocale-2.2"):new("OneBag")
L:RegisterTranslations("zhTW", function()
   return {
      ["Frame"]	= "框架",
      ["Frame Options"]	= "框架設定",
      ["Columns"]	= "欄",
      ["Sets the number of columns to use"]	= "設定每行的背包欄位數量",
      ["Scale"]	= "縮放",
      ["Sets the scale of the frame"]	= "設定框架縮放比例",
      ["Strata"]	= "層級",
      ["Sets the strata of the frame"]	= "設定框架顯示層級",
      ["Alpha"]	= "透明度",
      ["Sets the alpha of the frame"]	= "設定框架透明度",
      ["Locked"]	= "鎖定",
      ["Toggles the ability to move the frame"]	= "切換是否鎖定框架位置",
      ["Clamped"]	= "限制",
      ["Toggles the ability to drag the frame off screen."]	= "切換是否限制框架位置使其不能被拖動到螢幕邊緣之外。",
      ["Bag Break"] = "背包分隔",
      ["Sets wether to start a new row at the beginning of a bag."] = "設定是否在背包的起始位置另換新行。",
      ["Vertical Alignment"] = "垂直對齊",
      ["Sets wether to have the extra spaces on the top or bottom."] = "設定是否在頂端或底端顯示額外的空間。",
      ["Top"] = "頂端",
      ["Bottom"] = "底端",

      ["Show"]	= "顯示",
      ["Various Display Options"]	= "各種顯示設定",
      ["Counts"]	= "數目",
      ["Toggles showing the counts for special bags."]	= "切換是否顯示特殊包的格子數目。",
      ["Direction"]	= "方向",
      ["Forward"]	= "正向",
      ["Toggles direction the bags are shown"]	= "切換背包顯示順序",
      ["|cffff0000Reverse|r"]	= "|cffff0000反向|r",
      ["|cff00ff00Forward|r"]	= "|cff00ff00正向|r",
      ["Ammo Bag"]	= "彈藥包",
      ["Turns display of ammo bags on and off."]	= "切換是否顯示彈藥包。",
      ["Soul Bag"]	= "靈魂碎片背包",
      ["Turns display of soul bags on and off."]	= "切換是否顯示靈魂碎片背包。",
      ["Profession Bag"]	= "專業包",
      ["Turns display of profession bags on and off."]	= "切換是否顯示專業包。",
      ["Backpack"] = "背包",
      ["Turns display of your backpack on and off."] = "切換是否顯示背包。",
      ["First Bag"] = "第一個包",
      ["Turns display of your first bag on and off."] = "切換是否顯示第一個包。",
      ["Second Bag"] = "第二個包",
      ["Turns display of your second bag on and off."] = "切換是否顯示第二個包。",
      ["Third Bag"] = "第三個包",
      ["Turns display of your third bag on and off."] = "切換是否顯示第三個包。",
      ["Fourth Bag"] = "第四個包",
      ["Turns display of your fourth bag on and off."] = "切換是否顯示第四個包。",
      ["'s Bags"] = "的背包",      

      ["Colors"]	= "顏色",
      ["Different color code settings."]	= "各種顏色設定。",
      ["Mouseover Color"]	= "游標移至顏色",
      ["Changes the highlight color for when you mouseover a bag slot."]	= "變更游標移至背包欄位上時的高亮顏色。",
      ["Ammo Bag Color"]	= "彈藥包顏色",
      ["Changes the highlight color for Ammo Bags."]	= "變更彈藥包的高亮顏色。",
      ["Soul Bag Color"]	= "靈魂碎片背包顏色",
      ["Changes the highlight color for Soul Bags."]	= "變更靈魂碎片背包的高亮顏色。",
      ["Profession Bag Color"]	= "專業包顏色",
      ["Changes the highlight color for Profession Bags."]	= "變更專業包的高亮顏色。",
      ["Background Color"]	= "背景顏色",
      ["Changes the background color for the frame."]	= "變更框架背景顏色。",
      ["Highlight Glow"]	= "高亮發光",
      ["Turns hightlight glow on and off."]	= "開關高亮發光。",
      ["Rarity Coloring"]	= "品質顏色",
      ["Turns rarity coloring on and off."]	= "開關品質顏色。",

      ["Reset"]	= "重置",
      ["Reset the different colors."]	= "重置各種顏色設定。",
      ["Mouseover Color"]	= "游標移至顏色",
      ["Returns your mouseover color to the default."]	= "重置游標移至顏色為預設設定。",
      ["Ammo Slot Color"]	= "彈藥欄位顏色",
      ["Returns your ammo slot color to the default."]	= "重置彈藥欄位顏色為預設設定。",
      ["Soul Slot Color"]	= "靈魂碎片欄位顏色",
      ["Returns your soul slot color to the default."]	= "重置靈魂碎片欄位顏色為預設設定。",
      ["Profession Slot Color"]	= "專業欄位顏色",
      ["Returns your profession slot color to the default."]	= "重置專業欄位顏色為預設設定。",
      ["Background"]	= "背景",
      ["Returns your frame background to the default."]	= "重置背景顏色為預設設定。",
      ["Plow!"]	= "整理！",
      ["Organizes your bags."]	= "整理你的背包。",
      ["- Note: This option only appears if you have MrPlow installed"]	= "- 注意：只有當你安裝了 MrPlow 插件時才會出現此設定",

      ["Pick Locale"] = "選擇語言", 
      ["Sets the locale to use.  Will not take effect until you reload your UI."] = "設定語言。需要重載使用者界面。",

      ["%s ran in %s"]	= "%s 運行於 %s 下",
      ["Checking if bag %s is open"]	= "檢測背包 %s 是否是打開狀態",
      ["Opening bag %s"]	= "打開背包 %s",
      ["Closing bag %s"]	= "關閉背包 %s",

      ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "普通欄位已用：%s，靈魂碎片欄位已用：%s，專業欄位已用：%s，彈藥欄位已用：%s，彈藥品質：%s。",
      ["%s/%s Slots"]	= "%s/%s 欄位",
      ["%s/%s Ammo"]	= "%s/%s 彈藥欄位",
      ["%s/%s Soul Shards"]	= "%s/%s 靈魂碎片欄位",
      ["%s/%s Profession Slots"]	= "%s/%s 專業欄位",
      
      ["Menu"] = "選單"
   }
end)