-- Copyright © 2006 Mazin Assanie
-- All Rights Reserved.
-- 
-- Permission to use, copy, modify, and distribute this software in any way
-- is not granted without expressed written agreement.  In the case that it
-- is granted, the above copyright notice and this paragraph must appear in
-- all copies, modifications, and distributions.
--
-- To contact the author of this work, use mazzlefizz@gmail.com 
-- For more information on copyright, visit http://copyright.gov/ or http://whatiscopyright.org/
--

function Setup_DART16(profileName)

    if DART_Settings then
        DART_Settings[profileName] = {
		[1] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 0,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 7,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Mazzle Bottom1",
			["height"] = 238,
			["yoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 7,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["hidebg"] = 1,
			["drawlayer"] = "ARTWORK",
			["disablemouse"] = 1,
			["disableMousewheel"] = 1,
			["color"] = {
				["r"] = 0.7058823529411764,
				["g"] = 0.7333333333333333,
				["b"] = 0.7215686274509804,
			},
			["bgalpha"] = 0,
			["scripts"] = {
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 470,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = 0,
			},
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Bottom1",
			["alpha"] = 1,
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["bottom"] = "0",
				["right"] = 5,
				["left"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
		},
		[2] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 7,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Mazzle Bottom2",
			["height"] = 238,
			["yoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_1",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["hidebg"] = true,
			["drawlayer"] = "ARTWORK",
			["disablemouse"] = 1,
			["disableMousewheel"] = 1,
			["color"] = {
				["r"] = 0.7058823529411764,
				["g"] = 0.7333333333333333,
				["b"] = 0.7215686274509804,
			},
			["bgalpha"] = 1,
			["scripts"] = {
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 558,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = 0,
			},
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Bottom2",
			["alpha"] = 1,
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["Backdrop"] = {
				["top"] = "0",
				["edgeSize"] = "0",
				["tileSize"] = "0",
				["bottom"] = "0",
				["right"] = "0",
				["left"] = "0",
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
		},
		[3] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 7,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Mazzle Bottom3",
			["height"] = 238,
			["yoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_2",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["hidebg"] = true,
			["drawlayer"] = "ARTWORK",
			["borderalpha"] = 1,
			["disableMousewheel"] = 1,
			["color"] = {
				["r"] = 0.7058823529411764,
				["g"] = 0.7333333333333333,
				["b"] = 0.7215686274509804,
			},
			["bgalpha"] = 1,
			["scripts"] = {
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 558,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = 0,
			},
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Bottom3",
			["alpha"] = 1,
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
		},
		[4] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["color"] = {
				["r"] = 0.7058823529411764,
				["g"] = 0.7333333333333333,
				["b"] = 0.7215686274509804,
			},
			["attachpoint"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Mazzle Bottom4",
			["height"] = 238,
			["yoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Bottom4",
			["bgalpha"] = 1,
			["borderalpha"] = 1,
			["disableMousewheel"] = 1,
			["blendmode"] = "DISABLE",
			["parent"] = "UIParent",
			["scripts"] = {
			},
			["highlightcolor"] = {
				["r"] = 0.9490196078431372,
				["g"] = 1,
				["b"] = 0.9647058823529412,
			},
			["width"] = 470,
			["highlightalpha"] = 0,
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["hidebg"] = 1,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["padding"] = 0,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["bottom"] = "0",
				["right"] = 5,
				["left"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
		},
		[5] = {
			["bgcolor"] = {
				["r"] = 0.5843137254901961,
				["g"] = 0,
				["b"] = 0.00392156862745098,
			},
			["disablemouse"] = 1,
			["parent"] = "DUF_TargetFrame",
			["attachpoint"] = {
				[1] = 8,
				[2] = 3,
				[3] = 5,
				[4] = 5,
			},
			[4] = 19,
			["text"] = {
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["justifyV"] = 5,
				["fontsize"] = 19,
				["yoffset"] = 0,
			},
			["name"] = "Mazzle Target Cave",
			["height"] = 256,
			["yoffset"] = {
				[1] = 143,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 0.8100000000000001,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 1,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 0,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\FloatingCave",
			["bordercolor"] = {
				["r"] = 0.5294117647058824,
				["g"] = 0.5333333333333333,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["disableMousewheel"] = 1,
			["bgalpha"] = 1,
			["borderalpha"] = 1,
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["top"] = "0",
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["bottom"] = "0",
				["right"] = 5,
				["left"] = "5",
			},
			["width"] = 256,
			["scripts"] = {
			},
			["hidebg"] = 1,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["alpha"] = 1,
			["blendmode"] = "DISABLE",
			["padding"] = 0,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["color"] = {
				["r"] = 0.5294117647058824,
				["g"] = 0.5529411764705883,
				["b"] = 0.5450980392156862,
			},
		},
		[6] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			[4] = 1,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "HUD Player Health",
			["height"] = 256,
			["yoffset"] = {
				[1] = "512",
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 9,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -100,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\HL",
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["borderalpha"] = 1,
			["disableMousewheel"] = 1,
			["attachpoint"] = {
				[1] = 8,
				[2] = 3,
				[3] = 5,
				[4] = 5,
			},
			["drawlayer"] = "ARTWORK",
			["scripts"] = {
			},
			["alpha"] = 0,
			["width"] = 128,
			["highlightalpha"] = 0.3,
			["hidebg"] = 1,
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bgalpha"] = 1,
			["padding"] = 0,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 0.301961,
					["g"] = 0.121569,
					["b"] = 1,
				},
				["text"] = "Text",
				["alpha"] = 1,
				["width"] = 58,
				["fontsize"] = 20,
				["height"] = 106,
				["justifyH"] = 4,
				["attachto"] = 2,
				["xoffset"] = -3,
				["attachpoint"] = 5,
				["justifyV"] = 8,
				["yoffset"] = -1,
			},
			["color"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
		},
		[7] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			[4] = 1,
			["bordercolor"] = {
				["r"] = 0.09019607843137255,
				["g"] = 1,
				["b"] = 0,
			},
			["name"] = "HUD Player Background",
			["height"] = 256,
			["yoffset"] = {
				[1] = 0,
				[2] = -5,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_6",
				[2] = "",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["hidebg"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["drawlayer"] = "ARTWORK",
			["disableMousewheel"] = 1,
			["bgalpha"] = 1,
			["blendmode"] = "DISABLE",
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["width"] = 128,
			["borderalpha"] = 1,
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\HBL",
			["alpha"] = 0,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["padding"] = 0,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = "-3",
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = "-1",
			},
		},
		[8] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = 0,
			},
			["name"] = "HUD Player Mana",
			["xoffset"] = {
				[1] = -6,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = -73,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "LOW",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_6",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["blendmode"] = "DISABLE",
			["hidebg"] = 1,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0.0196078431372549,
			},
			["drawlayer"] = "ARTWORK",
			["disableMousewheel"] = 1,
			["parent"] = "UIParent",
			["alpha"] = 0,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 64,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\ML",
			["disablemouse"] = 1,
			["Backdrop"] = {
				["bottom"] = 11,
				["right"] = 12,
				["left"] = 11,
				["top"] = 12,
				["tileSize"] = 32,
				["edgeSize"] = 32,
				["tile"] = true,
			},
			["scripts"] = {
			},
			["height"] = 256,
			["padding"] = 0,
			["bordertexture"] = "Interface\\DialogFrame\\UI-DialogBox-Border",
			["bgalpha"] = 1,
		},
		[9] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 0.62,
			[4] = 1,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 0.301961,
					["g"] = 0.121569,
					["b"] = 1,
				},
				["text"] = "Text",
				["alpha"] = 1,
				["width"] = 58,
				["fontsize"] = 20,
				["height"] = 106,
				["justifyH"] = 4,
				["attachto"] = 2,
				["xoffset"] = -3,
				["attachpoint"] = 5,
				["justifyV"] = 8,
				["yoffset"] = -1,
			},
			["name"] = "HUD Target Health",
			["height"] = 256,
			["yoffset"] = {
				[1] = "0",
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "LOW",
			["scale"] = 1,
			["coords"] = {
				[1] = 1,
				[2] = 0,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_6",
				[2] = "",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 9,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = "200",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\HL",
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["disableMousewheel"] = 1,
			["borderalpha"] = 0.44,
			["attachpoint"] = {
				[1] = 8,
				[2] = 3,
				[3] = 5,
				[4] = 5,
			},
			["drawlayer"] = "ARTWORK",
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["width"] = 128,
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = 1,
			["hide"] = true,
			["alpha"] = 0,
			["padding"] = 0,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["color"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 1,
			},
		},
		[10] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			[4] = 1,
			["bordercolor"] = {
				["r"] = 0.09019607843137255,
				["g"] = 1,
				["b"] = 0,
			},
			["name"] = "HUD Target Background",
			["height"] = 256,
			["yoffset"] = {
				[1] = "0",
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 1,
				[2] = 0,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_9",
				[2] = "",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["hidebg"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["drawlayer"] = "ARTWORK",
			["disableMousewheel"] = 1,
			["bgalpha"] = 1,
			["blendmode"] = "DISABLE",
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["width"] = 128,
			["borderalpha"] = 1,
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\HBL",
			["alpha"] = 0,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["padding"] = 0,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = "-3",
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = "-1",
			},
		},
		[11] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0.0196078431372549,
			},
			["name"] = "HUD Target Mana",
			["xoffset"] = {
				[1] = 6,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = -73,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "LOW",
			["scale"] = 1,
			["coords"] = {
				[1] = 1,
				[2] = 0,
				[3] = nil --[[ nan ]],
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "DART_Texture_9",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 16,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["justifyV"] = 5,
				["yoffset"] = 0,
			},
			["hidebg"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["borderalpha"] = 1,
			["disableMousewheel"] = 1,
			["bordertexture"] = "Interface\\DialogFrame\\UI-DialogBox-Border",
			["hide"] = true,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 0,
			["width"] = 64,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\ML",
			["scripts"] = {
				[7] = "",
				[3] = "",
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["bgalpha"] = 1,
			["padding"] = 0,
			["Backdrop"] = {
				["bottom"] = 11,
				["right"] = 12,
				["left"] = 11,
				["top"] = 12,
				["tileSize"] = 32,
				["edgeSize"] = 32,
				["tile"] = true,
			},
			["height"] = nil --[[ nan ]],
		},
		[12] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 0.3333333333333333,
				["g"] = 0.02745098039215686,
				["b"] = 0.05490196078431373,
			},
			["bgalpha"] = 1,
			[4] = 257,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "HotSpotSE",
			["height"] = 25,
			["yoffset"] = {
				[1] = -4,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 1,
				[2] = 0,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 9,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["blendmode"] = "DISABLE",
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["attachpoint"] = {
				[1] = 9,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(7,this)",
				[4] = "GameTooltip:Hide()",
				[7] = "MazzleUI:HotSpot_Handle(7)",
			},
			["alpha"] = 1,
			["width"] = 25,
			["bordercolor"] = {
				["r"] = 0.05882352941176471,
				["g"] = 0.392156862745098,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["texture"] = "",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "KC Items",
				["alpha"] = 1,
				["width"] = 90,
				["justifyV"] = 8,
				["height"] = 20,
				["fontsize"] = 14,
				["attachto"] = 2,
				["xoffset"] = 0,
				["justifyH"] = 6,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["xoffset"] = {
				[1] = 3,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["parent"] = "UIParent",
		},
		[13] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			[4] = 257,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "Compass",
				["alpha"] = 1,
				["width"] = 100,
				["justifyH"] = 5,
				["xoffset"] = 0,
				["fontsize"] = 14,
				["attachto"] = 2,
				["height"] = 20,
				["justifyV"] = 2,
				["attachpoint"] = 2,
				["yoffset"] = 0,
			},
			["name"] = "HotSpotMinimap",
			["height"] = 18,
			["yoffset"] = {
				[1] = -5,
				[2] = "-5",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "MEDIUM",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 4,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["bgalpha"] = 1,
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
			["highlightalpha"] = 0.3,
			["alpha"] = 0,
			["width"] = 60,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 0.392156862745098,
				["r"] = 0.05882352941176471,
			},
			["scripts"] = {
				[7] = "MazzleUI:HotSpot_Handle(6)",
				[3] = "",
			},
			["hidebg"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0.3333333333333333,
				["g"] = 0,
				["r"] = 0,
			},
			["padding"] = 0,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		},
		[14] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 0.3333333333333333,
				["g"] = 0.02745098039215686,
				["b"] = 0.05490196078431373,
			},
			["bgalpha"] = 1,
			[4] = 257,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "HotSpotSW",
			["height"] = 25,
			["yoffset"] = {
				[1] = -5,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 1,
				[2] = 0,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 7,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["attachpoint"] = {
				[1] = 7,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 1,
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(5,this)",
				[4] = "GameTooltip:Hide()",
				[7] = "MazzleUI:HotSpot_Handle(5)",
			},
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["width"] = 25,
			["bordercolor"] = {
				["r"] = 0.05882352941176471,
				["g"] = 0.392156862745098,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["texture"] = "",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "KC Items",
				["alpha"] = 1,
				["width"] = 90,
				["justifyV"] = 8,
				["xoffset"] = 0,
				["justifyH"] = 6,
				["attachto"] = 2,
				["height"] = 20,
				["fontsize"] = 14,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["xoffset"] = {
				[1] = -5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["parent"] = "UIParent",
		},
		[15] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			[4] = 1000,
			["text"] = {
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 0.6745098039215687,
					["g"] = 0.6745098039215687,
					["b"] = 0.7294117647058823,
				},
				["text"] = "MazzleUI",
				["alpha"] = 1,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["justifyV"] = 5,
				["fontsize"] = 16,
				["yoffset"] = 0,
			},
			["name"] = "MazzleUI Button",
			["xoffset"] = {
				[1] = -17.22,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = 207.96,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "",
			["bgalpha"] = 0,
			["alpha"] = 1,
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(0,this)",
				[4] = "GameTooltip:Hide()\n",
				[7] = "MazzleUI:HotSpot_Handle(0)",
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 76,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["hidebg"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["attachto"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["height"] = 23,
			["color"] = {
				["r"] = 0.6823529411764706,
				["g"] = 0.6823529411764706,
				["b"] = 0.6823529411764706,
			},
		},
		[16] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 0.8941176470588235,
				["g"] = 1,
				["b"] = 0.2549019607843137,
			},
			["bgalpha"] = 1,
			[4] = 1000,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "HotSpotE",
			["height"] = 25,
			["yoffset"] = {
				[1] = 215,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "",
			["attachpoint"] = {
				[1] = 9,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 0.1,
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(4,this)",
				[4] = "GameTooltip:Hide()",
				[7] = "MazzleUI:HotSpot_Handle(4)",
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 25,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "ItemRack",
				["alpha"] = 1,
				["width"] = 120,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["justifyH"] = 4,
				["attachto"] = 2,
				["height"] = 14,
				["fontsize"] = 16,
				["justifyV"] = 5,
				["hide"] = true,
			},
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["hidebg"] = 1,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightalpha"] = 0.3,
			["padding"] = 5,
			["xoffset"] = {
				[1] = 5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["parent"] = "UIParent",
		},
		[17] = {
			["bgcolor"] = {
				["r"] = 0.5843137254901961,
				["g"] = 0,
				["b"] = 0.00392156862745098,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 0.3215686274509804,
				["g"] = 0.3254901960784314,
				["b"] = 0.3254901960784314,
			},
			["bgalpha"] = 1,
			[4] = 19,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "NeedyList",
				["alpha"] = 1,
				["width"] = 100,
				["justifyV"] = 5,
				["xoffset"] = 0,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["fontsize"] = 16,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "HotSpotNE",
			["xoffset"] = {
				[1] = -366,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = "215",
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.4,
			["hidebg"] = 1,
			["attachpoint"] = {
				[1] = 9,
				[2] = 3,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
			["attachto"] = {
				[1] = 9,
				[2] = 1,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 1,
			["width"] = 25,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["texture"] = "",
			["bordercolor"] = {
				["r"] = 0.5294117647058824,
				["g"] = 0.5333333333333333,
				["b"] = 0,
			},
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(3,this)",
				[4] = "GameTooltip:Hide()",
				[7] = "MazzleUI:HotSpot_Handle(3)",
			},
			["padding"] = 0,
			["height"] = 25,
			["parent"] = "UIParent",
		},
		[18] = {
			["bgcolor"] = {
				["r"] = 0.5843137254901961,
				["g"] = 0,
				["b"] = 0.00392156862745098,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 0.5529411764705883,
				["g"] = 0.5450980392156862,
				["b"] = 0.5450980392156862,
			},
			["bgalpha"] = 1,
			[4] = 19,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "HotSpotW",
			["height"] = 25,
			["yoffset"] = {
				[1] = 214,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 7,
				[2] = 1,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "",
			["attachpoint"] = {
				[1] = 7,
				[2] = 3,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 1,
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(1,this)",
				[4] = "GameTooltip:Hide()",
				[7] = "MazzleUI:HotSpot_Handle(1)",
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 25,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "Quests",
				["alpha"] = 1,
				["width"] = 77,
				["justifyV"] = 5,
				["xoffset"] = 0,
				["justifyH"] = 6,
				["attachto"] = 2,
				["height"] = 20,
				["fontsize"] = 16,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["bottom"] = 5,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["tile"] = true,
			},
			["hidebg"] = 1,
			["bordercolor"] = {
				["r"] = 0.5294117647058824,
				["g"] = 0.5333333333333333,
				["b"] = 0,
			},
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["xoffset"] = {
				[1] = -4,
				[2] = "0",
				[3] = 0,
				[4] = 0,
			},
			["parent"] = "UIParent",
		},
		[19] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["color"] = {
				["r"] = 0.5294117647058824,
				["g"] = 0.5529411764705883,
				["b"] = 0.5450980392156862,
			},
			["bgalpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "Notebook",
				["alpha"] = 1,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["fontsize"] = 16,
				["justifyV"] = 5,
				["hide"] = true,
			},
			["name"] = "HotSpotNW",
			["height"] = 25,
			["yoffset"] = {
				[1] = "215",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 7,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["blendmode"] = "DISABLE",
			["borderalpha"] = 1,
			["disableMousewheel"] = 1,
			["attachpoint"] = {
				[1] = 7,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["scripts"] = {
				[3] = "MazzleUI:HotSpot_Handle(2,this)",
				[4] = "GameTooltip:Hide()",
				[7] = "MazzleUI:HotSpot_Handle(2)",
			},
			["alpha"] = 1,
			["width"] = 25,
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["xoffset"] = {
				[1] = 366,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "",
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["padding"] = 0,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["bottom"] = "0",
				["right"] = 5,
				["left"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		},
		[20] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			[4] = 257,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "HotSpotToT",
			["height"] = 27,
			["yoffset"] = {
				[1] = 137,
				[2] = "-5",
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "MEDIUM",
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
				[2] = "",
			},
			["framelevel"] = 4,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 8,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["blendmode"] = "DISABLE",
			["disableMousewheel"] = 1,
			["drawlayer"] = "ARTWORK",
			["bgalpha"] = 1,
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = 16,
				["edgeSize"] = 16,
				["bottom"] = 5,
			},
			["width"] = 244,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 0.392156862745098,
				["r"] = 0.05882352941176471,
			},
			["scripts"] = {
				[7] = "MazzleUI:HotSpot_Handle(8)",
				[3] = "",
			},
			["hidebg"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0.3333333333333333,
				["g"] = 0,
				["r"] = 0,
			},
			["padding"] = 0,
			["alpha"] = 0,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "Compass",
				["alpha"] = 1,
				["width"] = 100,
				["fontsize"] = 14,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["justifyV"] = 2,
				["attachpoint"] = 2,
				["yoffset"] = 0,
			},
		},
		["INITIALIZED1.5"] = true,
		["INITIALIZED1.0d"] = true,
		["optionsscale"] = 1,
		["updatespeed"] = 5,
		["autolock"] = 1,
		["INITIALIZED1.1"] = true,
	}
    end
end