local L = LibStub("AceLocale-3.0"):NewLocale("ErrorMonster", "esES")
if not L then return end

L["Shows the current filters and their ID."] = "Muestra los filtros actuales y su ID."
L["Adds the given filter to the ignore list."] = "A\195\177ade el filtro a la lista de ignorados."
L["<filter>"] = "<filtro>"
L["Removes the given filter or ID from the filter list."] = "Elimina el filtro o ID de la lista de filtros."
L["Adding filter: "] = "A\195\177adiendo filtro: "
L["Removing filter: "] = "Eliminando filtro: "
L["Filter not found: "] = "Filtro no encontrado: "
L["Active filters:"] = "Filtros activos: "
L["Throttle errors at the given rate in seconds."] = "Acelerar los errores al ritmo determinado en segundos."
L["Go berserk and eat all the errors."] = "Volverse loco y comerse todos los errores."
L["Teach your ErrorMonster to aggro on other message types."] = "Ense\195\177ar a tu ErrorMonster a aggrear a otros tipos de mensajes."
L["Error messages."] = "Mensajes de error."
L["Information messages."] = "Mensajes de informaci\195\179n."
L["System messages."] = "Mensajes de sistema."
L["System messages"] = "Mensajes de sistema"
L["|cffff0000Ignore|r"] = "|cffff0000Ignorar|r"
L["|cff00ff00Aggro|r"] = "|cff00ff00Aggro|r"

L["list"] = "lista"
L["add"] = "a\195\177adir"
L["remove"] = "eliminar"
L["throttle"] = "acelerar"
L["berserk"] = "berserk"
L["aggro"] = "aggro"
L["error"] = "error"
L["information"] = "informaci\195\179n"
L["system"] = "sistema"

