DBM.AddGuiTab("Battlegrounds", DBMGUI_TAB_BG_TEXT, DBMGUI_TAB_BG_TITLE_TEXT);
DBM.AddGuiTab("BC Battlegrounds", DBMGUI_TAB_BG_TEXT, DBMGUI_TAB_BG_TITLE_TEXT, true);
DBM.AddMsg(string.format(DBM_BOSS_MOD_LOADED, DBM_BATTLEGROUND));