local L = AceLibrary("AceLocale-2.2"):new("ExperienceFu")

L:RegisterTranslations("zhTW", function() return {
    ["Current XP"] = "當前經驗",
    ["Display Value as..."] = "顯示數值為...",
    ["Display Values"] = "顯示數值",
    ["Display various XP statistics"] = "顯示多種經驗統計",
    ["Gained"] = "獲取",
    ["Hide Text at maximum level"] = "達到Lv60時隱藏文字",
    ["Level"] = "等級",
    ["Pet XP"] = "寵物經驗",
    ["Remaining"] = "剩餘",
    ["Reset session"] = "重置本次連線統計",
    ["Rest XP"] = "經驗值雙倍獎勵",
    ["Show XP/hour"] = "顯示 經驗值/小時",
    ["Show current XP percent"] = "顯示當前經驗值百分比",
    ["Show current XP until level"] = "顯示升級所需經驗值",
    ["Show current XP value"] = "顯示目前經驗值",
    ["Show current XP"] = "顯示目前經驗值",
    ["Show in relation to level"] = "顯示當前等級相對的經驗",
    ["Show percent"] = "顯示百分比",
    ["Show pet XP percent"] = "顯示寵物經驗百分比",
    ["Show pet XP until level"] = "顯示寵物升級需要經驗",
    ["Show pet XP value"] = "顯示寵物經驗值",
    ["Show pet XP"] = "顯示寵物經驗值",
    ["Show rest XP percent"] = "顯示獎勵經驗值百分比",
    ["Show rest XP value"] = "顯示獎勵經驗值",
    ["Show rest XP"] = "顯示獎勵經驗值",
    ["Show time to level"] = "顯示升級預估時間",
    ["Show value"] = "顯示值",
    ["Statistics"] = "統計",
    ["Time this level"] = "本等級遊戲時間",
    ["Time this session"] = "本次遊戲時間",
    ["Time to level for this level"] = "升級時間(按等級效率)",
    ["Time to level for this session"] = "升級時間(按連接效率)",
    ["Toggle between showing experience as an absolute or in relation to time."] = "切換顯示絕對值或者針對時間的相對值",
    ["Total XP this level"] = "目前等級所需經驗",
    ["Total XP this session"] = "本次連線總經驗",
    ["Total time played"] = "總遊戲時間",
    ["View as Remaining XP"] = "顯示為升級所需經驗值",
    ["XP/hour this level"] = "目前等級之 經驗/小時",
    ["XP/hour this session"] = "本次連接 經驗/小時",
} end)

