-- Copyright © 2006 Mazin Assanie
-- All Rights Reserved.
-- 
-- Permission to use, copy, modify, and distribute this software in any way
-- is not granted without expressed written agreement.  In the case that it
-- is granted, the above copyright notice and this paragraph must appear in
-- all copies, modifications, and distributions.
--
-- To contact the author of this work, use mazzlefizz@gmail.com 
-- For more information on copyright, visit http://copyright.gov/ or http://whatiscopyright.org/
--

MazzleUI_AddOn_DB = {
    { addonName = "!!!Libs",
                  core = true,
    },
    { addonName = "!!Warmup",
    },
    { addonName = "!ClearFont",
                  core = true,
    },
    { addonName = "!ImprovedErrorFrame",
                  core = true,
    },
    { addonName = "!OmniCC",
                  core = true,
                  notInPackage = {cpu = true, minimum = true},
    },
    { addonName = "Ace",
                  core = true,
    },
    { addonName = "AceGUI",
                  core = true,
    },
    { addonName = "AdvancedTradeSkillWindow",
                  core = true,
                  notInPackage = { loading = true, minimum = true},
    },
    { addonName = "AHFavorites",
                  core = true,
                  auctions = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AH_QuickSearch",
                  core = true,
                  auctions = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AH_ShowBid",
                  core = true,
                  auctions = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AlphaMap",
                  core = true,
                  notInPackage = { loading = true, minimum = true},
    },
    { addonName = "AntiDaze",
                  core = true,
                  classes = {Hunter = true, },
    },
    { addonName = "AnsweringMachine",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AtlasLoot",
                  core = true,
                  notInPackage = { loading = true, minimum = true},
    },
    { addonName = "AQAutoMount",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AuctionFilterPlus",
                  core = true,
                  auctions = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AutoAcceptInvite",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AutoBar",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "AutoBarConfig",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "Autorank",
                  core = true,
                  notInPackage = { cpu = true, minimum = true},
    },
    { addonName = "avbars",
                  core = true,
                  pvp = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "BigWigs",
                  core = true,
                  raiding = true,
    },
    { addonName = "BigWigs_CThunAssist",
                  core = true,
                  raiding = true,
    },
    { addonName = "BigWigs_NefCount",
                  core = true,
                  raiding = true,
    },
    { addonName = "BookOfCrafts",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "BookOfTracks",
                  core = true,
    },
    { addonName = "CECB_Options",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "CEnemyCastBar",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "CharactersViewer",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "ChatCast",
                  core = true,
                  notInPackage = {cpu = true, minimum = true},
    },
    { addonName = "Chatmanager",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "ClassMasterLoot",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "clearBlizzard",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "Clique",
                  core = true,
                  classes = {Paladin = true, Shaman = true, Druid = true, Mage = true, Priest = true, },
                  notInPackage = { loading = true, minimum = true},
    },
    { addonName = "ColorComboPoints",
                  core = true,
                  classes = {Druid = true, Rogue = true, },
    },
    { addonName = "CT_Viewport",
                  core = true,
    },
    { addonName = "DamageMeters",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "DeuceCommander",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "Detox",
                  core = true,
                  classes = {Paladin = true, Shaman = true, Druid = true, Mage = true, Priest = true, },
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "DiscordActionBars",
                  core = true,
    },
    { addonName = "DiscordActionBarsOptions",
                  core = true,
    },
    { addonName = "DiscordArt",
                  core = true,
    },
    { addonName = "DiscordArtOptions",
                  core = true,
    },
    { addonName = "DiscordFrameModifier",
                  core = true,
    },
    { addonName = "DiscordFrameModifierOptions",
                  core = true,
    },
    { addonName = "DiscordLibrary",
                  core = true,
    },
    { addonName = "DiscordMiniSpellbook",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "DiscordUnitFrames",
                  core = true,
    },
    { addonName = "DiscordUnitFramesOptions",
                  core = true,
    },
    { addonName = "DmgCalc",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "DoTimer",
                  core = true,
                  classes = {Warlock = true, },
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "EasyCopy",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "EQCompare",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "Fastcast",
                  core = true,
                  classes = {Warrior = true, Paladin = true, Shaman = true, Hunter = true, Druid = true, Mage = true, Warlock = true, Priest = true, },
                  notInPackage = {minimum = true},
    },
    { addonName = "FinderReminder",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FixMe",
                  core = true,
    },
    { addonName = "FruityLoots",
                  core = true,
    },
    { addonName = "FuBar",
                  core = true,
    },
    { addonName = "FuBar-compat-1.2",
                  core = true,
    },
    { addonName = "FuBar_AmmoFu",
                  core = true,
                  classes = { Warrior = true, Hunter = true, Rogue = true, },
    },
    { addonName = "FuBar_AnkhTimerFu",
                  core = true,
                  classes = {Shaman = true, },
    },
    { addonName = "FuBar_Aspect",
                  core = true,
                  classes = {Hunter = true, },
    },
    { addonName = "FuBar_BattlegroundFu",
                  core = true,
                  pvp = true,
    },
    { addonName = "FuBar_CombatInfoFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "Fubar_DamageMetersFu2",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FuBar_DurabilityFu",
                  core = true,
    },
    { addonName = "FuBar_ExperienceFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FuBar_FactionsFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FuBar_FriendsFu",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "FuBar_GuildFu",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "FuBar_HonorFu",
                  core = true,
                  pvp = true,
    },
    { addonName = "FuBar_KCIFu",
                  core = true,
                  notInPackage = { loading = true,  minimum = true},
    },
    { addonName = "FuBar_MageFu",
                  core = true,
                  classes = {Mage = true, },
    },
    { addonName = "FuBar_MailFu",
                  core = true,
    },
    { addonName = "FuBar_MoneyFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FuBar_NameToggleFu",
                  core = true,
    },
    { addonName = "FuBar_PetInfo",
                  core = true,
                  classes = {Hunter = true, Warlock = true, },
    },
    { addonName = "FuBar_ReagentFu",
                  core = true,
                  classes = {Paladin = true, Shaman = true, Druid = true, Rogue = true, Mage = true, Warlock = true, Priest = true, },
    },
    { addonName = "FuBar_SkillsPlusFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FuBar_SWStatsFu",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "FuBar_TankPointsFu",
                  core = true,
                  classes = {Warrior = true, Paladin = true, Druid = true, },
    },
    { addonName = "FuBar_ToFu",
                  core = true,
                  notInPackage = {minimum = true, loading = true},
    },
    { addonName = "FuBar_TopScoreFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "FuBar_VolumeFu",
                  core = true,
    },
    { addonName = "Gatherer",
    },
    { addonName = "GFW_FeedOMatic",
                  core = true,
                  classes = {Hunter = true, },
    },
    { addonName = "GFW_HuntersHelper",
                  core = true,
                  classes = {Hunter = true, },
    },
    { addonName = "GMail",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "gfxToggle",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "IDCard",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "ItemRack",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "ItemRackFu",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "KC_Items",
                  core = true,
                  notInPackage = { loading = true, minimum = true},
    },
    { addonName = "KC_Mobility",
                  core = true,
    },
    { addonName = "KLHThreatMeter",
    },
    { addonName = "Lexan",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "LoadIT",
                  core = true,
    },
    { addonName = "LootScroll",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MailTo",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MapScroll",
                  core = true,
    },
    { addonName = "MarsQuestOrganizer",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "Mazz3D",
                  core = true, mazzle = true,
    },
    { addonName = "Mazzifier",
                  core = true, mazzle = true,
    },
    { addonName = "MazzleHelp",
                  core = true, mazzle = true,
    },
    { addonName = "MazzleOptions",
                  core = true, mazzle = true,
    },
    { addonName = "MazzleUI",
                  core = true, mazzle = true,
    },
    { addonName = "Mendeleev",
                  core = true,
                  notInPackage = { loading = true, minimum = true},
    },
    { addonName = "Merchantbags",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MobHealth",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MonkeyBuddy",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MonkeyLibrary",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MonkeyQuest",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MonkeyQuestLog",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "MovableBags",
                  core = true,
    },
    { addonName = "myBindings",
                  core = true,
    },
    { addonName = "Necrosis",
                  core = true,
                  classes = {Warlock = true, },
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "NeedyList",
                  core = true,
                  classes = {Paladin = true, Shaman = true, Druid = true, Mage = true, Priest = true, },
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "oRA2",
                  core = true,
                  raiding = true,
    },
    { addonName = "PartySpotter",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "Prat",
                  core = true,
                  notInPackage = {},
    },
    { addonName = "Recap",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "sct",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "sctd",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "sctd_options",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "sct_cooldowns",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "sct_options",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "SHunterTimers",
                  core = true,
                  classes = {Hunter = true, },
    },
    { addonName = "SimpleActionSets",
                  
    },
    { addonName = "SimpleCombatLog",
                  core = true,
    },
    { addonName = "SmartAssist",
                  core = true,
                  notInPackage = {cpu = true, minimum = true},
    },
    { addonName = "SmartAssistOptions",
                  core = true,
                  notInPackage = {cpu = true, minimum = true},
    },
    { addonName = "SpecialTalent",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "SpecialTalentUI",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "sRaidFrames",
                  core = true,
                  raiding = true,
    },
    { addonName = "StatusWindow",
                  core = true,
    },
    { addonName = "SuperInspect",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "SuperInspect_UI",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "SW_Stats",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "TargetButtons",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "TheoryCraft",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "Timex",
                  core = true,
    },
    { addonName = "TinyPad",
                  core = true,
                  notInPackage = {loading = true},
    },
    { addonName = "TinyTip",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "TinyTipExtras",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "TinyTipOptions",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "TrinketMenu",
                  core = true,
                  notInPackage = { loading = true, cpu = true, minimum = true},
    },
    { addonName = "WhoFavorites",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "WhoTip",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "WitchHunt",
                  core = true,
                  notInPackage = {minimum = true, cpu = true},
    },
    { addonName = "xcalc",
                  core = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "XRS",
                  core = true,
                  raiding = true,
                  notInPackage = {minimum = true},
    },
    { addonName = "!BugGrabber",
                  mazzle = true,
    },
    { addonName = "BugSack",
                  mazzle = true,
    },
    { addonName = "AddonCore",
                  mazzle = true,
    },
    { addonName = "CommandHistory",
                  mazzle = true,
    },
    { addonName = "DevTools",
                  mazzle = true,
    },
    { addonName = "ForAllIndentsAndPurposes",
                  mazzle = true,
    },
    { addonName = "Inspector",
                  mazzle = true,
    },
    { addonName = "MazzleMage",
                  mazzle = true,
    },
    { addonName = "NetherWatch",
                  mazzle = true,
    },
    { addonName = "Phoenix",
                  mazzle = true,
    },
    { addonName = "RepToGo",
                  mazzle = true,
    },
    { addonName = "tradeDispenser",
                  mazzle = true,
    },
}