StatusWindow.strings = {
	VERSION = "StatusWindow |cff00ff00",
	CANCEL = "Cancel",
	UISCALE = "Use UI Scale",
	SCALE = "Scale",
	WIDTH = "Width",
	NEWPLAYER = "StatusWindow: new player ",
	RESET = "StatusWindow: Clear saved variables for new version - sorry!",
	UPDATE = "Updating to StatusWindow version %.2f",
	MENU = "StatusWindow Options",
	HSTACK = "Arrange Horizontally",
	BORDER = "Show Border",
	BACKGROUND = "Show Background",
	WINDOW = "Window ",
	CONFIG = "Module Config",
	ADDONMENU = "Enable Addon Menu",
	ADDONMENU_DISABLE = "This change will take effect when the game is restarted (or /console reloadui)",

	-- Module strings
	OFFSET = "Clock Offset",
	CLOCKTYPE = "24h clock",
	HPTICK = "HP/tick: |c00FFFFFF",
	MANATICK = "MP/tick: |c00FFFFFF",
	DURABILITYLABEL = "Armor: ",
	FPSLABEL = "FPS",
	
	HELP1 = "Configuring StatusWindow",
	HELP2 = "A StatusWindow contains up to 10 panes",
	HELP3 = "Right click panes in the right column to configure them",
	HELP4 = "Click on a window's button in the left column to select it",
	HELP5 = "Drag panes into the open slots in the middle for the selected window",
	HELP6 = "Select display options for the window as desired",
	HELP7 = "Hold down the Alt key while dragging a StatusWindow to move it",
}