
TheoryCraft_SetBonuses = {
	["Frostfire Regalia"] = {
		[1] = {
			["pieces"] = 2,
			["text"] = "Reduces cooldown on your Evocation by 1 minute.",
		},
		[2] = {
			["pieces"] = 4,
			["text"] = "Gives your Mage Armor a chance when struck by a harmful spell to increase resistance against that school of magic by 35 for 30 sec.",
		},
		[3] = {
			["pieces"] = 6,
			["text"] = "Your damage spells have a chance to cause your target to take up to 200 increased damage from subsequent spells.",
		},
		[4] = {
			["pieces"] = 8,
			["text"] = "Your damage spells have a chance to displace you, causing the next spell cast to generate no threat.",
		},
	},
	["Nemesis Raiment"] = {
		[1] = {
			["pieces"] = 5,
			["text"] = "Your pet gains 20 stamina and 130 spell resistance against all schools of magic.",
		},
		[2] = {
			["pieces"] = 8,
			["text"] = "Reduces the threat generated by your Destruction spells by 20%.",
		},
	},
	["Doomcaller's Attire"] = {
		[1] = {
			["pieces"] = 3,
			["text"] = "5% increased damage on your Immolate spell.",
		},
		[2] = {
			["pieces"] = 5,
			["text"] = "Reduces the mana cost of Shadow Bolt by 15%.",
		},
	},
	["Demoniac's Threads"] = {
		[1] = {
			["pieces"] = 2,
			["text"] = "Increases damage and healing done by magical spells and effects by up to 12.",
		},
		[2] = {
			["pieces"] = 3,
			["text"] = "Increases the damage of Corruption by 2%.",
		},
		[3] = {
			["pieces"] = 5,
			["text"] = "Decreases the cooldown of Death Coil by 15%.",
		},
	},
	["Netherwind Regalia"] = {
		[1] = {
			["pieces"] = 5,
			["text"] = "Increases the radius of Arcane Explosion, Flamestrike, and Blizzard by 25%.",
		},
		[2] = {
			["pieces"] = 8,
			["text"] = "10% chance after casting Arcane Missiles, Fireball, or Frostbolt that your next spell with a casting time under 10 seconds cast instantly.",
		},
	},
	["Arcanist Regalia"] = {
		[1] = {
			["pieces"] = 3,
			["text"] = "Increases damage and healing done by magical spells and effects by up to 18.",
		},
		[2] = {
			["pieces"] = 5,
			["text"] = "Decreases the magical resistances of your spell targets by 10.",
		},
		[3] = {
			["pieces"] = 8,
			["text"] = "Decreases the threat generated by your spells by 15%.",
		},
	},
	["Enigma Vestments"] = {
		[1] = {
			["pieces"] = 3,
			["text"] = "Your Blizzard spell has a 30% chance to be uninterruptible.",
		},
		[2] = {
			["pieces"] = 5,
			["text"] = "Grants +5% increased spell hit chance for 20 sec when one of your spells is resisted.",
		},
	},
}
TheoryCraft_MitigationMobs = {
}
TheoryCraft_MitigationPlayers = {
}
