-- AtlasLoot loot tables deDE locale file
-- NOTE: THIS FILE IS AUTO-GENERATED BY A TOOL, ANY MANUALLY CHANGE MIGHT BE OVERWRITTEN.
-- $Id$

if GetLocale() == "deDE" then
local Process = function(category,check,data) if not AtlasLoot_Data["AtlasLootExpansionItems"][category] or #AtlasLoot_Data["AtlasLootExpansionItems"][category] ~= check then return end for i = 1,#data do if(data[i] and data[i]~="") then AtlasLoot_Data["AtlasLootExpansionItems"][category][i][3] = data[i] end end data = nil end

end