if( GetLocale() ~= "koKR" ) then
	return
end
AfflictedLocals = setmetatable({
	["ALT + Drag to move the frame anchor."] = "ALT + Drag 앵커 프레임 이동.",
	["Reset Afflicted configuration as you were using Afflicted2."] = "Reset Afflicted configuration as you were using Afflicted2.",
	
	-- Cmd
	["Slash commands"] = "Afflicted 슬래쉬 명령어",
	["- clear - Clears all running timers."] = "- clear - 작동중인 타이머들을 초기화합니다.",
	["- ui - Opens the configuration for Afflicted."] = "- ui - Afflicted 설정창을 엽니다.",
	["- test - Shows test timers in Afflicted."] = "- test - Afflicted 테스트창을 보여줍니다.",
	
	-- GUI
	["General"] = "일반",
	
	["None"] = "없음",
	["Combat text"] = "전투 텍스트",
	["Party"] = "파티",
	["Raid"] = "공격대",
	["Raid warning"] = "공격대 경보",
	["Middle of screen"] = "화면 중앙",
	["Chat frame #%d"] = "채팅 프레임 #%d",

	["Everywhere else"] = "일반 지역",
	["Battlegrounds"] = "전장",
	["Arenas"] = "투기장",
	["Raid instances"] = "공격대 던전",
	["Party instances"] = "파티 던전",
	
	["Enable inside"] = "Enable inside",
	
	["Bars"] = "Bars",
	["Icons"] = "Icons",
	
	["Display"] = "Display",
	
	["Font name"] = "폰트 이름",
	["Font size"] = "폰트 사이즈",
	["Texture"] = "텍스쳐",
	["Width"] = "넓이",
	["Only timers of people you have targeted, or focused will be triggered. They will not be removed if you change targets however."] = "Only timers of people you have targeted, or focused will be triggered. They will not be removed if you change targets however.",
	["Only show target/focus timers"] = "대상/주시 타이머만 보이기",
	["Only show triggered name in text"] = "Only show triggered name in text",
	["Bar only"] = "Bar only",
	["Show timer anchors"] = "Show timer anchors",
	["Show the anchors that lets you drag timer groups around."] = "Show the anchors that lets you drag timer groups around.",
	["Global display setting, changing these will change all the anchors settings.\nNOTE: These values do not reflect each anchors configuration, this is just a quick way to set all of them to the same thing."] = "Global display setting, changing these will change all the anchors settings.\nNOTE: These values do not reflect each anchors configuration, this is just a quick way to set all of them to the same thing.",
	["Grow up"] = "위로 표시",
	["Instead of adding everything from top to bottom, timers will be shown from bottom to top."] = "Instead of adding everything from top to bottom, timers will be shown from bottom to top.",
	["Display style"] = "Display style",
	["Scale"] = "크기",
	["How big the actual timers should be."] = "How big the actual timers should be.",
	["Max timers"] = "최대 타이머",
	["Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed."] = "Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed.",
	["Configuration that only applies to bar displays."] = "Configuration that only applies to bar displays.",
	["Instead of showing both the spell name and the triggered name, only the name will be shown in the bar."] = "Instead of showing both the spell name and the triggered name, only the name will be shown in the bar.",
	
	["Spells"] = "주문",
	["Spell categories"] = "주문 카테고리",
	["Search spells"] = "주문 검색",
	
	["All"] = "All",
	
	["Duration disabled"] = "지속시간 비활성",
	["Duration: %d (%s)"] = "지속시간: %d (%s)",
	["Cooldown disabled"] = "재사용 대기시간 비활성",
	["Cooldown: %d (%s)"] = "재사용 대기시간: %d (%s)",
	
	["Disable duration"] = "비활성된 지속시간",
	["Duration"] = "지속 시간",
	
	["Disable cooldown"] = "비활성된 재사용 대기시간",
	["Cooldown"] = "재사용 시간",
	["Spell cooldown"] = "주문 재사용 시간",
	["Anchor"] = "앵커",
	["Spell timer"] = "주문 타이머",
	["Spell data"] = "Spell data",
	["Type"] = "Type",
	["Spell type, buffs are things that the player actually gains, casts are anything thats an instant cast spell, summoned objects are things such as totems, and created objects are traps."] = "Spell type, buffs are things that the player actually gains, casts are anything thats an instant cast spell, summoned objects are things such as totems, and created objects are traps.",
	["Casts"] = "Casts",
	["Summoned objects"] = "Summoned objects",
	["Created objects"] = "Created objects",
	["Buffs"] = "Buffs",
	["Class from"] = "Class from",
	["The class that actually casts this spell, used for categorization."] = "The class that actually casts this spell, used for categorization.",
	["Cooldown anchor"] = "재사용 대기시간 앵커",
	["Spells linked to this one"] = "Spells linked to this one",
	["Spells that are specifically linked to this one by a spell id. This is basically lower ranked spells, and you only need to set this if you're adding by spell id... and even then you don't really have to."] = "Spells that are specifically linked to this one by a spell id. This is basically lower ranked spells, and you only need to set this if you're adding by spell id... and even then you don't really have to.",
	["Advanced configuration linked to more internal functions.\nValues are separated by commas.\nDO NOT edit these if you do not know what you are doing, you do not have to touch them 99% of the time."] = "Advanced configuration linked to more internal functions.\nValues are separated by commas.\nDO NOT edit these if you do not know what you are doing, you do not have to touch them 99% of the time.",
	["Reset when this is used"] = "Reset when this is used",
	["Spells that should have there cooldown reset when this one is used, think Preparation or Iceblock."] = "Spells that should have there cooldown reset when this one is used, think Preparation or Iceblock.",
	["Advanced"] = "Advanced",
	["Delete"] = "삭제",
	["Spells that were added manually will be deleted, however spells that are added by default are simply reset next update."] = "Spells that were added manually will be deleted, however spells that are added by default are simply reset next update.",
	["Are you REALLY sure you want to delete this spell?"] = "Are you REALLY sure you want to delete this spell?",
	["Add new spell by name or spell id"] = "Add new spell by name or spell id",
	["A spell with that name already exists."] = "A spell with that name already exists.",
	["No spell name entered."] = "No spell name entered.",
	["Add a new spell to Afflicted, you can add it either by the spell name or spell id. However, if you add it by spell name then you must match the casing Blizzard uses as it is case sensitive."] = "Add a new spell to Afflicted, you can add it either by the spell name or spell id. However, if you add it by spell name then you must match the casing Blizzard uses as it is case sensitive.",
	["New spell"] = "새 주문",
	["New anchor"] = "새 앵커",
	["Anchors"] = "앵커들",
	["Add a new anchor to Afflicted that timers can be displayed in."] = "Add a new anchor to Afflicted that timers can be displayed in.",
	["Anchor name"] = "앵커 이름",
	["No anchor name entered."] = "No anchor name entered.",
	["An anchor with that name already exists."] = "An anchor with that name already exists.",

	["Announcement text for when timers are triggered in this anchor. You can use *spell for the spell name, and *target for the person who triggered it (if any)."] = "Announcement text for when timers are triggered in this anchor. You can use *spell for the spell name, and *target for the person who triggered it (if any).",
	["Announce text"] = "알림 텍스트",
	["Destination"] = "Destination",
	["Text color"] = "텍스트 색상",
	["Announcements"] = "알림",
	["Group name to redirect bars to, this lets you show Afflicted timers under another addons bar group. Requires the bars to be created using GTB, and the bar display to be enabled for this anchor."] = "Group name to redirect bars to, this lets you show Afflicted timers under another addons bar group. Requires the bars to be created using GTB, and the bar display to be enabled for this anchor.",
	["Redirection"] = "Redirection",
	["Fade time"] = "Fade time",
	["How many seconds it should take after a bar is finished for it to fade out."] = "How many seconds it should take after a bar is finished for it to fade out.",
	["Scale"] = "크기",
	["Icon position"] = "아이콘 위치",
	["Display type"] = "Display type",
	["Enable anchor"] = "앵커 사용",
	["Allows timers to be shown under this anchor, if the anchor is disabled you won't see any timers."] = "Allows timers to be shown under this anchor, if the anchor is disabled you won't see any timers.",
	["Display"] = "Display",
	["Grow up"] = "위로 표시",
	["Instead of adding everything from top to bottom, timers will be shown from bottom to top."] = "Instead of adding everything from top to bottom, timers will be shown from bottom to top.",
	["Max timers"] = "최대 타이머",
	["Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed."] = "Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed.",
	["Redirect bars to group"] = "Redirect bars to group",
	["Enable announcements"] = "알림 사용",
	["Alert text color, only applies to local outputs."] = "Alert text color, only applies to local outputs.",
	["Start message"] = "시작 메세지",
	["Message to show when a timer is started in this anchor."] = "Message to show when a timer is started in this anchor.",
	["Ended message"] = "메세지 사용",
	["Message to show when a timer ends inside this anchor."] = "Message to show when a timer ends inside this anchor.",
	["Left"] = "왼쪽",
	["Right"] = "오른쪽",
	["Anchors that were added manually will be deleted, default anchors will be reset to default settings if you delete them. Disable default anchors to stop timers from showing."] = "Anchors that were added manually will be deleted, default anchors will be reset to default settings if you delete them. Disable default anchors to stop timers from showing.",
	["Are you REALLY sure you want to delete this anchor?"] = "Are you REALLY sure you want to delete this anchor?",
	["Move spells in this anchor to"] = "Move spells in this anchor to",
	["You have to choose which anchor spells should be moved to when this one is deleted."] = "You have to choose which anchor spells should be moved to when this one is deleted.",
	
	["Arena spells"] = "투기장 주문",
	["2 vs 2"] = "2 vs 2",
	["3 vs 3"] = "3 vs 3",
	["5 vs 5"] = "5 vs 5",
	["Spells that should be enabled inside a specific arena bracket."] = "Spells that should be enabled inside a specific arena bracket.",

	-- Class localization
	["DRUID"] = "드루이드",
	["DEATHKNIGHT"] = "죽음의 기사",
	["WARRIOR"] = "전사",
	["PALADIN"] = "성기사",
	["ROGUE"] = "도적",
	["MAGE"] = "마법사",
	["PRIEST"] = "사제",
	["WARLOCK"] = "흑마법사",
	["HUNTER"] = "사냥꾼",
	["SHAMAN"] = "주술사",	
}, {__index = AfflictedLocals})